import { MetadataRoute } from 'next';

const BASE_URL = 'https://mallan.nyc';

/**
 * Dynamic robots.txt generation for Next.js
 *
 * STRATEGY: Selective AI crawler access.
 * - AI SEARCH bots (GPTBot, ChatGPT-User, PerplexityBot, ClaudeBot, etc.)
 *   are ALLOWED on brand/expertise pages so AI search engines can recommend us.
 * - AI TRAINING-ONLY crawlers (CCBot, img2dataset) remain fully blocked.
 * - ALL bots are blocked from MLS listing data, API routes, and private areas
 *   to comply with REBNY RLS data protection rules.
 * - SEO scrapers remain blocked (no value, just bandwidth).
 */

// Pages that contain MLS/IDX data or private content — blocked for ALL bots
const PRIVATE_AND_MLS_PATHS = [
  '/listing/',     // Individual MLS listing pages (IDX data)
  '/search',       // Search results (IDX data)
  '/admin/',
  '/admin',
  '/agent/',
  '/agent',
  '/client-access/',
  '/client-access',
  '/demo/',
  '/demo',
  '/style-preview/',
  '/style-preview',
  '/leads/',
  '/leads',
  '/api/',
  '/api',
  '/sign-in',
  '/sign-up',
  '/portal/',
  '/portal',
  '/reset-password',
  '/offer-status',
  '/saved-searches',
  '/favorites',
  '/compare',
  '/unsubscribe',
  '/crm/',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // ── AI SEARCH BOTS ──
      // Allow on brand/expertise pages, block on MLS data pages.
      // These bots power ChatGPT search, Perplexity, Claude, Apple Intelligence.
      // They need to see our about, agents, neighborhoods, contact pages
      // to recommend us in AI search results.
      {
        userAgent: 'GPTBot',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'ChatGPT-User',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'PerplexityBot',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'ClaudeBot',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'anthropic-ai',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'Applebot-Extended',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'Amazonbot',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      {
        userAgent: 'YouBot',
        allow: [
          '/about',
          '/agents',
          '/agents/',
          '/contact',
          '/sell',
          '/buy',
          '/rent',
          '/neighborhoods',
          '/manhattan',
          '/manhattan/',
          '/brooklyn',
          '/brooklyn/',
          '/queens',
          '/queens/',
          '/bronx',
          '/bronx/',
          '/staten-island',
          '/staten-island/',
          '/market',
          '/open-houses',
          '/fair-housing',
          '/sop',
          '/terms',
          '/privacy',
          '/reasonable-accommodations',
        ],
        disallow: PRIVATE_AND_MLS_PATHS,
      },
      // ── AI TRAINING-ONLY CRAWLERS ── (fully blocked, no search value)
      {
        userAgent: 'CCBot',
        disallow: '/',
      },
      {
        userAgent: 'Bytespider',
        disallow: '/',
      },
      {
        userAgent: 'Diffbot',
        disallow: '/',
      },
      {
        userAgent: 'Webzio',
        disallow: '/',
      },
      {
        userAgent: 'img2dataset',
        disallow: '/',
      },
      // ── SEO SCRAPERS ── (fully blocked, no value)
      {
        userAgent: 'AhrefsBot',
        disallow: '/',
      },
      {
        userAgent: 'SemrushBot',
        disallow: '/',
      },
      {
        userAgent: 'DotBot',
        disallow: '/',
      },
      {
        userAgent: 'MJ12bot',
        disallow: '/',
      },
      {
        userAgent: 'DataForSeoBot',
        disallow: '/',
      },
      {
        userAgent: 'BLEXBot',
        disallow: '/',
      },
      {
        userAgent: 'PetalBot',
        disallow: '/',
      },
      {
        userAgent: 'serpstatbot',
        disallow: '/',
      },
      // ── DEFAULT ── allow legitimate search engines (Google, Bing, etc.)
      {
        userAgent: '*',
        allow: '/',
        disallow: PRIVATE_AND_MLS_PATHS,
      },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}
