/**
 * live-truth.ts — the live-Cotality-verified membership facts the canonical search
 * contract is built on.
 *
 * AUTHORITY (AGENTS.md §7 — "Cotality is the sole authority, always live, never a copy"):
 *   The live authority is `data/cotality-enums.live.json`, regenerated by
 *   `npm run cotality:pull && npm run cotality:verify`. This module carries the DURABLE
 *   MEMBERSHIP facts (which enum values exist / are filterable) as typed constants that are
 *   a PROJECTION of that file — `live-truth.test.ts` binds these constants to the live file
 *   and fails if they drift. Live COUNTS/populations are intentionally NOT frozen here
 *   (they drift daily and must be read live).
 *
 * This module is PURE DATA + provenance. No I/O, no policy. It bundles no large JSON.
 */

export const LIVE_AUTHORITY = Object.freeze({
  /** The generated, verified live mirror of the Cotality $metadata enums. */
  path: 'data/cotality-enums.live.json',
  /** Regeneration command — run before freezing any enum-derived constant. */
  regenerate: 'npm run cotality:pull && npm run cotality:verify',
  source: 'https://api.cotality.com/trestle/odata/$metadata',
  /**
   * Date this projection was last verified against a live pull.
   *
   * Was '2026-07-05' and had gone six weeks stale while carrying provider
   * statements the August live verification disproved.
   *
   * NOTE: this is the date `npm run cotality:pull && npm run cotality:verify`
   * was actually RUN and passed (181 enums), not a value read from the generated
   * file — `data/cotality-enums.live.json` records `pulled_at: null`, so it
   * cannot date itself. That weakens drift detection and is worth fixing in
   * `scripts/cotality/pull-enums.mjs` separately.
   */
  verifiedAgainstPull: '2026-08-19',
});

/**
 * StandardStatus — the ONLY filterable status field (11 members). Membership is durable truth;
 * populations are live-only. `ActiveUnderContract` exists in metadata but is 0 live — see
 * DEAD_OR_INVALID_VALUES (kept as a fail-closed classify guard, never a query axis).
 */
export const STANDARD_STATUS_MEMBERS = Object.freeze([
  'Active', 'ActiveUnderContract', 'Canceled', 'Closed', 'ComingSoon',
  'Delete', 'Expired', 'Hold', 'Incomplete', 'Pending', 'Withdrawn',
] as const);

/**
 * MlsStatus — members exist in metadata but the field is NOT OData-filterable
 * (provider-suppressed, HTTP 400 on $filter). It may be READ from a record; NEVER a query axis.
 */
export const MLS_STATUS_FILTERABLE = false;

/** PropertyType — only these two are populated live; the exact rental value has NO space. */
export const PROPERTY_TYPE_SALE = 'Residential';
export const PROPERTY_TYPE_RENTAL = 'ResidentialLease';

/**
 * CommonInterest — ALL 13 live members (data/cotality-enums.live.json). Co-op = StockCooperative
 * (there is NO `Cooperative` member). The first five are the NYC segmentation classes used by
 * ownership.ts; the remaining eight are valid-but-unsegmented members — classified 'other', never
 * silently dropped to 'unknown'.
 */
export const COMMON_INTEREST_MEMBERS = Object.freeze([
  'Condominium', 'StockCooperative', 'Condop', 'RentalBuilding', 'None',
  'BareLandCondominium', 'CommunityApartment', 'CoOwnership', 'Freehold',
  'Leasehold', 'Other', 'PlannedDevelopment', 'Timeshare',
] as const);

/** The five CommonInterest values that map to an NYC ownership segmentation class. */
export const COMMON_INTEREST_SEGMENTATION = Object.freeze([
  'Condominium', 'StockCooperative', 'Condop', 'RentalBuilding', 'None',
] as const);

/**
 * Permission / ListingPermission — live members. Participant-only = `Private`.
 * NEITHER enum contains `OwnerOptOut` — the owner-opt-out gate signal is NOT a permission value
 * (see DEAD_OR_INVALID_VALUES; the gate is enforced via the DB column, and must fail closed until
 * a live field/value is confirmed). Members list is the compliance-relevant subset used by the gate.
 */
export const PERMISSION_PRIVATE = 'Private';

/**
 * Values the repo has historically hardcoded that live truth CONTRADICTS. Diagnostics/tests flag them.
 * `keepAsFailClosedGuard` = may remain ONLY as a documented fail-closed legacy/compliance guard,
 * never as live search logic.
 */
export const DEAD_OR_INVALID_VALUES = Object.freeze([
  { value: 'ActiveUnderContract', field: 'StandardStatus', reason: '0 live; Pending is the live in-contract status', keepAsFailClosedGuard: true },
  { value: 'Cooperative', field: 'CommonInterest', reason: 'not a live member; co-op is StockCooperative', keepAsFailClosedGuard: false },
  { value: 'Residential Lease', field: 'PropertyType', reason: 'invalid (space); live value is ResidentialLease', keepAsFailClosedGuard: false },
  { value: 'SingleFamilyTownhouse', field: 'PropertySubType', reason: 'not a live member (400); real member is Townhouse', keepAsFailClosedGuard: false },
  // CORRECTED 2026-08-20. The reason field previously recommended detecting new
  // development "via PublicRemarks/DevelopmentStatus". That heuristic is now
  // removed from both Search paths: matching prose cannot be verified against any
  // provider field, and a listing whose remarks say "brand new" is not new
  // construction. `NewConstructionYN` IS a live filterable Boolean (951 Active),
  // despite an older repo claim that it is not exposed on IDX Plus.
  { value: 'NewConstruction', field: 'PropertySubType', reason: 'not a live member (400); use the NewConstructionYN Boolean (live, filterable, 951 Active) — NOT PublicRemarks prose', keepAsFailClosedGuard: false },
  { value: 'OwnerOptOut', field: 'Permission', reason: 'NOT a live Permission/ListingPermission member — owner-opt-out must fail closed until a live field/value is confirmed', keepAsFailClosedGuard: true /* COMPLIANCE Gate 1: do NOT remove on field-truth alone */ },
  { value: 'InteriorFeatures', field: '(amenity field)', reason: 'live enum key is InteriorOrRoomFeatures — amenity mappings using InteriorFeatures are needs_probe', keepAsFailClosedGuard: false },
] as const);
