/**
 * live-truth.ts — the live-Cotality-verified membership facts the canonical search
 * contract is built on.
 *
 * AUTHORITY (AGENTS.md §7 — "Cotality is the sole authority, always live, never a copy"):
 *   The live authority is `data/cotality-enums.live.json`, regenerated by
 *   `npm run cotality:pull && npm run cotality:verify`. This module carries the DURABLE
 *   MEMBERSHIP facts (which enum values exist / are filterable) as typed constants that are
 *   a PROJECTION of that file — `live-truth.test.ts` binds these constants to the live file
 *   and fails if they drift. Live COUNTS/populations are intentionally NOT frozen here
 *   (they drift daily and must be read live).
 *
 * This module is PURE DATA + provenance. No I/O, no policy. It bundles no large JSON.
 */

export const LIVE_AUTHORITY = Object.freeze({
  /** The generated, verified live mirror of the Cotality $metadata enums. */
  path: 'data/cotality-enums.live.json',
  /** Regeneration command — run before freezing any enum-derived constant. */
  regenerate: 'npm run cotality:pull && npm run cotality:verify',
  source: 'https://api.cotality.com/trestle/odata/$metadata',
  /** The pull date recorded in the live file at the time this projection was last verified. */
  verifiedAgainstPull: '2026-09-05',
});

/**
 * StandardStatus — the ONLY filterable status field (11 members). Membership is durable truth;
 * populations are live-only. `ActiveUnderContract` exists in metadata but is 0 live — see
 * DEAD_OR_INVALID_VALUES (kept as a fail-closed classify guard, never a query axis).
 */
export const STANDARD_STATUS_MEMBERS = Object.freeze([
  'Active', 'ActiveUnderContract', 'Canceled', 'Closed', 'ComingSoon',
  'Delete', 'Expired', 'Hold', 'Incomplete', 'Pending', 'Withdrawn',
] as const);

/**
 * MlsStatus — members exist in metadata but the field is NOT OData-filterable
 * (provider-suppressed, HTTP 400 on $filter). It may be READ from a record; NEVER a query axis.
 */
export const MLS_STATUS_FILTERABLE = false;

/** PropertyType — only these two are populated live; the exact rental value has NO space. */
export const PROPERTY_TYPE_SALE = 'Residential';
export const PROPERTY_TYPE_RENTAL = 'ResidentialLease';

/**
 * CommonInterest — ALL 13 live members (data/cotality-enums.live.json). Co-op = StockCooperative
 * (there is NO `Cooperative` member). The first five are the NYC segmentation classes used by
 * ownership.ts; the remaining eight are valid-but-unsegmented members — classified 'other', never
 * silently dropped to 'unknown'.
 */
export const COMMON_INTEREST_MEMBERS = Object.freeze([
  'Condominium', 'StockCooperative', 'Condop', 'RentalBuilding', 'None',
  'BareLandCondominium', 'CommunityApartment', 'CoOwnership', 'Freehold',
  'Leasehold', 'Other', 'PlannedDevelopment', 'Timeshare',
] as const);

/** The five CommonInterest values that map to an NYC ownership segmentation class. */
export const COMMON_INTEREST_SEGMENTATION = Object.freeze([
  'Condominium', 'StockCooperative', 'Condop', 'RentalBuilding', 'None',
] as const);

/**
 * Permission / ListingPermission — live members. Participant-only = `Private`.
 * NEITHER enum contains `OwnerOptOut` — the owner-opt-out gate signal is NOT a permission value
 * (see DEAD_OR_INVALID_VALUES; the gate is enforced via the DB column, and must fail closed until
 * a live field/value is confirmed). Members list is the compliance-relevant subset used by the gate.
 */
/**
 * Live PropertyType members (pull 2026-09-05). Under StandardStatus eq 'Active' only
 * Residential and ResidentialLease are populated; the other eleven are 0 (Validator 2026-09-05).
 */
export const PROPERTY_TYPE_MEMBERS = Object.freeze([
  'BusinessOpportunity', 'CommercialLease', 'CommercialSale', 'DisasterReliefRental', 'Farm', 'HighRise', 'Land',
  'ManufacturedInPark', 'MultiFamily', 'Residential', 'ResidentialIncome', 'ResidentialLease', 'Specialty',
] as const);

/**
 * Live StructureType members (pull 2026-09-05). Multi-value field; executed with the bare-string
 * `StructureType has '<member>'` form (Validator 2026-09-05 §D/§J). Carrier of Mallan's Townhouse type.
 */
export const STRUCTURE_TYPE_MEMBERS = Object.freeze([
  'Apartment', 'Cabin', 'Dock', 'Duplex', 'Flex', 'FreeStandingBuilding', 'HighRise', 'HotelMotel', 'House',
  'Industrial', 'LowRise', 'ManufacturedHouse', 'MidRise', 'MixedUse', 'MultiFamily', 'None', 'Office', 'Other',
  'Quadruplex', 'Retail', 'Townhouse', 'Triplex', 'Warehouse',
] as const);

/**
 * CityRegion is a plain string field with NO lookup, so it is not in the enums file. These are its
 * live values on both active universes (Contract/Data Validator re-check 2026-09-05, item 4: the five
 * sale counts sum exactly to the universe). `StatenIsland` has no space. Re-verify live, never infer.
 */
export const CITY_REGION_VALUES = Object.freeze(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'StatenIsland'] as const);

export const PERMISSION_PRIVATE = 'Private';

/**
 * Values the repo has historically hardcoded that live truth CONTRADICTS. Diagnostics/tests flag them.
 * `keepAsFailClosedGuard` = may remain ONLY as a documented fail-closed legacy/compliance guard,
 * never as live search logic.
 */
export const DEAD_OR_INVALID_VALUES = Object.freeze([
  { value: 'ActiveUnderContract', field: 'StandardStatus', reason: '0 live; Pending is the live in-contract status', keepAsFailClosedGuard: true },
  { value: 'Cooperative', field: 'CommonInterest', reason: 'not a live member; co-op is StockCooperative', keepAsFailClosedGuard: false },
  { value: 'Residential Lease', field: 'PropertyType', reason: 'invalid (space); live value is ResidentialLease', keepAsFailClosedGuard: false },
  { value: 'SingleFamilyTownhouse', field: 'PropertySubType', reason: 'not a live member (400); real member is Townhouse', keepAsFailClosedGuard: false },
  { value: 'NewConstruction', field: 'PropertySubType', reason: 'not a live member (400); detected via PublicRemarks/DevelopmentStatus', keepAsFailClosedGuard: false },
  { value: 'OwnerOptOut', field: 'Permission', reason: 'NOT a live Permission/ListingPermission member — owner-opt-out must fail closed until a live field/value is confirmed', keepAsFailClosedGuard: true /* COMPLIANCE Gate 1: do NOT remove on field-truth alone */ },
  { value: 'InteriorFeatures', field: '(amenity field)', reason: 'live enum key is InteriorOrRoomFeatures — amenity mappings using InteriorFeatures are needs_probe', keepAsFailClosedGuard: false },
] as const);
