/**
 * GENERATED — do not edit. `node scripts/search/generate-neighborhood-identities.mjs`
 *
 * Canonical neighbourhood identities from the FULL live Cotality feed:
 * 591,409 rows, 592 pages, not truncated, read 2026-08-31.
 * Universe: ALL Property rows — no PropertyType restriction.
 *
 * IDENTITY IS (borough × normalised name). The census disproved global name
 * uniqueness — 124 of 632 folded names span more than one CityRegion.
 *
 * WHICH borough a name means is a MALLAN decision, not a count. Marble Hill is
 * Bronx 58 / Manhattan 12 in the feed and is legally MANHATTAN, so a plurality
 * rule returns the wrong answer. Decisions live in the generator with an owner
 * and a reason; the observed evidence is preserved uninterpreted in
 * artifacts/neighborhood-borough-resolution.json.
 *
 * 651 identities, 233 offered, 38 names left AMBIGUOUS
 * (no decision and no borough at the declared floor). A bare ambiguous name
 * resolves to NOTHING and must be qualified — it is never auto-assigned.
 *
 * Evidence: artifacts/subdivision-full-feed-2026-08-31.json
 */

export interface NeighborhoodIdentity {
  /** The ONE label a broker sees. Carries the borough when the name is ambiguous. */
  readonly label: string;
  /** Every raw Cotality spelling behind it. The union executes. */
  readonly spellings: readonly string[];
  readonly rows: number;
  /** Provider CityRegion value. NEVER null — it is part of the identity. */
  readonly borough: string;
  /** The borough label a broker reads. `StatenIsland` -> `Staten Island`. */
  readonly boroughLabel: string;
  /** Whether the browser autocomplete offers it. Execution ignores this. */
  readonly offered: boolean;
}

export const NEIGHBORHOOD_IDENTITIES: readonly NeighborhoodIdentity[] = Object.freeze([
  {"label":"Allerton","spellings":["Allerton"],"rows":10,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Alphabet City","spellings":["Alphabet City"],"rows":428,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Ancram","spellings":["Ancram"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Annadale","spellings":["Annadale"],"rows":22,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Arden Heights","spellings":["Arden Heights"],"rows":16,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Arlington","spellings":["Arlington"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Arrochar","spellings":["Arrochar"],"rows":6,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Arverne","spellings":["Arverne"],"rows":16,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Astoria","spellings":["Astoria","ASTORIA"],"rows":7444,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Astoria Heights","spellings":["Astoria Heights"],"rows":10,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Auburndale","spellings":["Auburndale"],"rows":27,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Bath Beach","spellings":["Bath Beach"],"rows":170,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"BATTERY","spellings":["BATTERY"],"rows":107,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Battery Park","spellings":["Battery Park"],"rows":81,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Battery Park City","spellings":["Battery Park City"],"rows":4270,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Bay Ridge","spellings":["Bay Ridge","BAYRIDGE"],"rows":2418,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Bay Terrace, Queens","spellings":["Bay Terrace"],"rows":42,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Bay Terrace, Staten Island","spellings":["Bay Terrace"],"rows":17,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Baychester","spellings":["Baychester","BAYCHESTER"],"rows":27,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Bayside","spellings":["Bayside"],"rows":120,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Bayswater","spellings":["Bayswater"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"BED-STUY","spellings":["BED-STUY","Bed Stuy"],"rows":155,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Bedford Park","spellings":["Bedford Park","BEDFORDPARK"],"rows":96,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Bedford-Stuyvesant","spellings":["Bedford-Stuyvesant","Bedford - Stuyvesant","Bedford Stuyvesant","Bedford/Stuyvesant"],"rows":10319,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Beechhurst","spellings":["Beechhurst"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Beechurst","spellings":["Beechurst"],"rows":12,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Beekman","spellings":["Beekman","BEEKMAN"],"rows":959,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Beekman Place","spellings":["Beekman Place"],"rows":36,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Bellaire","spellings":["Bellaire"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Belle Harbor","spellings":["Belle Harbor"],"rows":87,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Bellerose","spellings":["Bellerose"],"rows":48,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Belmont","spellings":["Belmont"],"rows":75,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Belmont | Little Ita","spellings":["Belmont | Little Ita"],"rows":10,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Belmont | Little Italy","spellings":["Belmont | Little Italy"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"BENHURST","spellings":["BENHURST"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Bensonhurst","spellings":["Bensonhurst"],"rows":409,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Bergen Beach","spellings":["Bergen Beach","BERGENBEACH"],"rows":62,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Beverley Square West","spellings":["Beverley Square West"],"rows":3,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Birchwood Towers","spellings":["Birchwood Towers"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"BKLYNHTS","spellings":["BKLYNHTS"],"rows":95,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"BLHARBOR","spellings":["BLHARBOR"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Blissville","spellings":["Blissville"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Boerum","spellings":["Boerum"],"rows":14,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Boerum Hill","spellings":["Boerum Hill"],"rows":4365,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"BOERUMHL","spellings":["BOERUMHL"],"rows":65,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"BOROPARK","spellings":["BOROPARK"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Borough Park","spellings":["Borough Park"],"rows":239,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Bowery","spellings":["Bowery"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Bowne Park","spellings":["Bowne Park"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Breezy Point","spellings":["Breezy Point"],"rows":25,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Briarwood","spellings":["Briarwood"],"rows":212,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Brickwood Towers","spellings":["Brickwood Towers"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"BRIGHTON","spellings":["BRIGHTON"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Brighton Beach","spellings":["Brighton Beach"],"rows":369,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Broad Channel","spellings":["Broad Channel"],"rows":8,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Broadway Junction","spellings":["Broadway Junction"],"rows":4,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Bronx","spellings":["Bronx"],"rows":218,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Bronxdale","spellings":["Bronxdale"],"rows":17,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"BRONXOTHER","spellings":["BRONXOTHER","Bronx (Other)"],"rows":3,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Bronxwood","spellings":["Bronxwood"],"rows":14,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Brooklyn","spellings":["Brooklyn","BROOKLYN"],"rows":1173,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"BROOKLYN [ALL]","spellings":["BROOKLYN [ALL]"],"rows":27,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Brooklyn Heights","spellings":["Brooklyn Heights"],"rows":8779,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Brookville","spellings":["Brookville"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Brownsville","spellings":["Brownsville"],"rows":196,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Bryant Park","spellings":["Bryant Park"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Bulls Head","spellings":["Bulls Head"],"rows":19,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Bushwick","spellings":["Bushwick"],"rows":5812,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"BUSK","spellings":["BUSK"],"rows":111,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Cambria Heights","spellings":["Cambria Heights"],"rows":18,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Canarsie","spellings":["Canarsie","CANARSIE"],"rows":382,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"CARLGDNS","spellings":["CARLGDNS"],"rows":84,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"CARNEGIE","spellings":["CARNEGIE"],"rows":58,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Carnegie Hill","spellings":["Carnegie Hill"],"rows":3949,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Carroll Gardens","spellings":["Carroll Gardens"],"rows":4202,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Castle Hill","spellings":["Castle Hill"],"rows":6,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Castleton Corners","spellings":["Castleton Corners"],"rows":3,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Caton Park","spellings":["Caton Park"],"rows":3,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Catskill, Bronx","spellings":["Catskill"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Catskill, Brooklyn","spellings":["Catskill"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"CENTPKSTH","spellings":["CENTPKSTH"],"rows":64,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Central Harlem","spellings":["Central Harlem"],"rows":2404,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Central Park South","spellings":["Central Park South"],"rows":2254,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Central Park West","spellings":["Central Park West"],"rows":227,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Central Riverdale","spellings":["Central Riverdale"],"rows":244,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Central Village","spellings":["Central Village"],"rows":606,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Charleston","spellings":["Charleston"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Chelsea","spellings":["Chelsea","CHELSEA"],"rows":20075,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Chelsea / Flatiron","spellings":["Chelsea / Flatiron","Chelsea/Flatiron"],"rows":31,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Chelsea/Hudson Yards","spellings":["Chelsea/Hudson Yards"],"rows":2985,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Chinatown","spellings":["Chinatown"],"rows":1477,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Chinatown / Little I","spellings":["Chinatown / Little I"],"rows":8,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Chinatown Little Ita","spellings":["Chinatown Little Ita"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"City Island","spellings":["City Island"],"rows":48,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"City Line","spellings":["City Line","CITYLINE"],"rows":23,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Civic Center","spellings":["Civic Center"],"rows":122,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Claremont","spellings":["Claremont"],"rows":5,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Claremont Village","spellings":["Claremont Village"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Clason Point","spellings":["Clason Point","CLASONPOINT"],"rows":19,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Clearview","spellings":["Clearview"],"rows":13,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Cliffside Park","spellings":["Cliffside Park"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Clifton","spellings":["Clifton"],"rows":7,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"CLINTHL","spellings":["CLINTHL"],"rows":61,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Clinton","spellings":["Clinton","CLINTON"],"rows":8447,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Clinton / Hell's Kit","spellings":["Clinton / Hell's Kit"],"rows":129,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"CLINTON DUT","spellings":["CLINTON DUT"],"rows":4,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Clinton Hill","spellings":["Clinton Hill"],"rows":6886,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Clinton Hill/Ft Gree","spellings":["Clinton Hill/Ft Gree"],"rows":6,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"CNA","spellings":["CNA"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Cobble Hill","spellings":["Cobble Hill"],"rows":3159,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"COBBLEHL","spellings":["COBBLEHL"],"rows":58,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"College Point","spellings":["College Point"],"rows":26,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Columbia","spellings":["Columbia"],"rows":10,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Columbia Presb","spellings":["Columbia Presb"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Columbia St Waterfr","spellings":["Columbia St Waterfr","Columbia St Waterfr."],"rows":70,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia St Waterfro","spellings":["Columbia St Waterfro"],"rows":17,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia St Waterfront District","spellings":["Columbia St Waterfront District"],"rows":12,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia St. Waterfront","spellings":["Columbia St. Waterfront","COLUMBIASTWATERFRONT"],"rows":34,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia Street Wat","spellings":["Columbia Street Wat"],"rows":18,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia Street Wate","spellings":["Columbia Street Wate"],"rows":255,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia Street Waterfront","spellings":["Columbia Street Waterfront"],"rows":48,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Columbia Street Waterfront District","spellings":["Columbia Street Waterfront District"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia Street WD","spellings":["Columbia Street WD"],"rows":85,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Columbia Waterfront","spellings":["Columbia Waterfront"],"rows":76,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"COLUMBUSCIR","spellings":["COLUMBUSCIR"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Concord","spellings":["Concord"],"rows":7,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Concourse","spellings":["Concourse"],"rows":332,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Concourse Village","spellings":["Concourse Village"],"rows":175,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Coney Island","spellings":["Coney Island"],"rows":108,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"CONEYISL","spellings":["CONEYISL"],"rows":7,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Copake","spellings":["Copake"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Corona","spellings":["Corona"],"rows":95,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Country Club","spellings":["Country Club"],"rows":26,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Court Square","spellings":["Court Square"],"rows":1045,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Crotona Park East","spellings":["Crotona Park East"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Crown Heights","spellings":["Crown Heights"],"rows":6752,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"CROWNHEI","spellings":["CROWNHEI"],"rows":34,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"CYPRESS","spellings":["CYPRESS"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Cypress Hills","spellings":["Cypress Hills"],"rows":98,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Dash Estate","spellings":["Dash Estate"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Ditmars Park","spellings":["Ditmars Park"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Ditmars Steinway","spellings":["Ditmars Steinway","Ditmars-Steinway"],"rows":259,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Ditmas Park","spellings":["Ditmas Park","Ditmas park"],"rows":1396,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Ditmas Park West","spellings":["Ditmas Park West"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"DITMASPK","spellings":["DITMASPK"],"rows":44,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"DNU-Brooklyn","spellings":["DNU-Brooklyn"],"rows":31,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Dongan Hills","spellings":["Dongan Hills"],"rows":23,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Douglaston","spellings":["Douglaston"],"rows":38,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"DOWNTOWN [ALL]","spellings":["DOWNTOWN [ALL]"],"rows":27,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Downtown Brooklyn","spellings":["Downtown Brooklyn"],"rows":6988,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Downtown, Brooklyn","spellings":["Downtown"],"rows":249,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Downtown, Manhattan","spellings":["Downtown"],"rows":97,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"DTWNBKYN","spellings":["DTWNBKYN"],"rows":30,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"DUMBO","spellings":["Dumbo","DUMBO"],"rows":2211,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"DUMBO / Vinegar Hill","spellings":["DUMBO / Vinegar Hill","Dumbo - Vinegar Hill"],"rows":855,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill","spellings":["DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Dyker Heights","spellings":["Dyker Heights"],"rows":270,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"DYKERSHT","spellings":["DYKERSHT"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"E. Greenwich Village","spellings":["E. Greenwich Village"],"rows":871,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"East Elmhurst","spellings":["East Elmhurst"],"rows":115,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"East Flatbush","spellings":["East Flatbush"],"rows":828,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"East Flatbush-Farragut","spellings":["East Flatbush-Farragut"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"East Flushing","spellings":["East Flushing"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"East Harlem","spellings":["East Harlem"],"rows":4827,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"East Midwood","spellings":["East Midwood"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"East Morrisania","spellings":["East Morrisania"],"rows":3,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"East New York","spellings":["East New York"],"rows":562,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"East Tremont","spellings":["East Tremont"],"rows":26,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"East Village","spellings":["East Village"],"rows":9166,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"East Williamsburg","spellings":["East Williamsburg","EASTWILLIAMSBURG"],"rows":1943,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Eastchester","spellings":["Eastchester"],"rows":15,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Easthampton, Brooklyn","spellings":["Easthampton"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Easthampton, Manhattan","spellings":["Easthampton"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"EASTVILL","spellings":["EASTVILL"],"rows":157,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Edenwald","spellings":["Edenwald"],"rows":11,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Edgemere","spellings":["Edgemere"],"rows":6,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"EFLATBUS","spellings":["EFLATBUS"],"rows":9,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"EHARLEM","spellings":["EHARLEM"],"rows":47,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Elm Park","spellings":["Elm Park"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Elmhurst","spellings":["Elmhurst"],"rows":595,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Eltingville","spellings":["Eltingville","ELTINGVILLE"],"rows":22,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Emerson Hill","spellings":["Emerson Hill"],"rows":6,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"ENY","spellings":["ENY"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Erasmus","spellings":["Erasmus"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Essex Falls","spellings":["Essex Falls"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Estate Area","spellings":["Estate Area"],"rows":21,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Far Rockaway","spellings":["Far Rockaway"],"rows":33,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Farragut","spellings":["Farragut"],"rows":70,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"FASHCNTR","spellings":["FASHCNTR"],"rows":199,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Fashion District","spellings":["Fashion District"],"rows":5,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"FHAMIL","spellings":["FHAMIL"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Fieldston","spellings":["Fieldston"],"rows":235,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Financial District","spellings":["Financial District"],"rows":12619,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"FINLDIST","spellings":["FINLDIST"],"rows":243,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Fiske Terrace","spellings":["Fiske Terrace"],"rows":7,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Flatbush","spellings":["Flatbush","FLATBUSH"],"rows":2514,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Flatiron","spellings":["Flatiron","FLATIRON"],"rows":7601,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Flatiron District","spellings":["Flatiron District"],"rows":286,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"FLATLAND","spellings":["FLATLAND"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Flatlands","spellings":["Flatlands"],"rows":286,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Floral Park","spellings":["Floral Park"],"rows":15,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Flushing","spellings":["Flushing","FLUSHING"],"rows":689,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Flushing Heights","spellings":["Flushing Heights"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Fordham","spellings":["Fordham","FORDHAM"],"rows":218,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Fordham Heights","spellings":["Fordham Heights"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Fordham Manor","spellings":["Fordham Manor"],"rows":5,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Forest Hills","spellings":["Forest Hills"],"rows":2253,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Forest Hills Garden","spellings":["Forest Hills Garden"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Forest Hills Gardens","spellings":["Forest Hills Gardens"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Forest Park","spellings":["Forest Park"],"rows":6,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"FORHILLS","spellings":["FORHILLS"],"rows":31,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Fort George","spellings":["Fort George"],"rows":179,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Fort Greene","spellings":["Fort Greene"],"rows":5495,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Fort Hamilton","spellings":["Fort Hamilton"],"rows":709,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"FORTGRNE","spellings":["FORTGRNE"],"rows":52,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Fresh Kills","spellings":["Fresh Kills"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Fresh Meadows","spellings":["Fresh Meadows"],"rows":35,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Fulton Ferry","spellings":["Fulton Ferry"],"rows":63,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Garment District","spellings":["Garment District"],"rows":69,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"GDL","spellings":["GDL"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Georgetown","spellings":["Georgetown"],"rows":41,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Gerritsen Beach","spellings":["Gerritsen Beach"],"rows":61,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Glen Oaks","spellings":["Glen Oaks"],"rows":53,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Glendale","spellings":["Glendale"],"rows":122,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Gowanus","spellings":["Gowanus","GOWANUS"],"rows":1804,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Gramercy","spellings":["Gramercy","GRAMERCY"],"rows":930,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Gramercy Park","spellings":["Gramercy Park"],"rows":9542,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"GRANDCONCOURSE","spellings":["GRANDCONCOURSE"],"rows":34,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Graniteville","spellings":["Graniteville"],"rows":9,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Grant City","spellings":["Grant City"],"rows":8,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Grasmere","spellings":["Grasmere"],"rows":7,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Gravesend","spellings":["Gravesend"],"rows":319,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"GRAVESND","spellings":["GRAVESND"],"rows":3,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Great Kills","spellings":["Great Kills"],"rows":33,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Greenpoint","spellings":["Greenpoint","Green Point"],"rows":6308,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"GREENPT","spellings":["GREENPT"],"rows":85,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Greenridge","spellings":["Greenridge"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"GREENWD","spellings":["GREENWD"],"rows":15,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Greenwich Village","spellings":["Greenwich Village"],"rows":19695,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Greenwich Village/We","spellings":["Greenwich Village/We"],"rows":212,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Greenwich Village/West Village","spellings":["Greenwich Village/West Village"],"rows":84,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Greenwood","spellings":["Greenwood"],"rows":184,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Greenwood Heights","spellings":["Greenwood Heights"],"rows":1232,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"GRENVILL","spellings":["GRENVILL"],"rows":1327,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Grenwich Village","spellings":["Grenwich Village"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Grymes Hill","spellings":["Grymes Hill"],"rows":12,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Guttenberg","spellings":["Guttenberg"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"HAMHGTS","spellings":["HAMHGTS"],"rows":69,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Hamilton Heights","spellings":["Hamilton Heights"],"rows":3531,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Hammels","spellings":["Hammels"],"rows":9,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Harlem","spellings":["Harlem","HARLEM"],"rows":10103,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Harlem / Morningside","spellings":["Harlem / Morningside"],"rows":32,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"HDBH","spellings":["HDBH"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Heartland Village","spellings":["Heartland Village"],"rows":9,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Hell's Kitchen","spellings":["Hell's Kitchen","Hells Kitchen"],"rows":3164,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Highbridge","spellings":["Highbridge","High Bridge","HIGHBRIDGE"],"rows":88,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Highland Park","spellings":["Highland Park"],"rows":7,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Hillcrest","spellings":["Hillcrest"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Hillsdale","spellings":["Hillsdale"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Hoboken, Bronx","spellings":["Hoboken"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Hoboken, Brooklyn","spellings":["Hoboken"],"rows":7,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Hoboken, Manhattan","spellings":["Hoboken"],"rows":5,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Hollis","spellings":["Hollis"],"rows":22,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Hollis Hills","spellings":["Hollis Hills"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Holliswood","spellings":["Holliswood"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"HOMECRE","spellings":["HOMECRE"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Homecrest","spellings":["Homecrest"],"rows":183,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Howard Beach","spellings":["Howard Beach"],"rows":35,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Hudson Heights","spellings":["Hudson Heights"],"rows":2352,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Hudson Square","spellings":["Hudson Square"],"rows":683,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Hudson Yard","spellings":["Hudson Yard"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Hudson Yards","spellings":["Hudson Yards"],"rows":1160,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Hudson Yards / MSG","spellings":["Hudson Yards / MSG"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Hudson, Brooklyn","spellings":["Hudson"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Hudson, Manhattan","spellings":["Hudson"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Huguenot","spellings":["Huguenot"],"rows":17,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Hunters Point","spellings":["Hunters Point"],"rows":686,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Hunters Point-Sunnyside-West Maspeth","spellings":["Hunters Point-Sunnyside-West Maspeth","Hunters Point-sunnyside-west Maspeth"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Huntington","spellings":["Huntington"],"rows":13,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Hunts Point","spellings":["Hunts Point"],"rows":18,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Inwood","spellings":["Inwood","INWOOD"],"rows":1927,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Inwood / Washington","spellings":["Inwood / Washington"],"rows":43,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Inwood/Marble Hill","spellings":["Inwood/Marble Hill"],"rows":23,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"ITALCHIN","spellings":["ITALCHIN"],"rows":90,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Italy","spellings":["Italy"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Jackson Heights","spellings":["Jackson Heights","Jackson heights"],"rows":2281,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"JACOBJAV","spellings":["JACOBJAV"],"rows":22,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Jamaica","spellings":["Jamaica"],"rows":335,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Jamaica Center","spellings":["Jamaica Center"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Jamaica Estate","spellings":["Jamaica Estate"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Jamaica Estates","spellings":["Jamaica Estates"],"rows":203,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Jamaica Hills","spellings":["Jamaica Hills"],"rows":73,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Jersey City","spellings":["Jersey City"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Jersey City Downtown","spellings":["Jersey City Downtown"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"JKHTS","spellings":["JKHTS"],"rows":6,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"JMCA","spellings":["JMCA"],"rows":15,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"KENSINGT","spellings":["KENSINGT"],"rows":20,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Kensingtn/Ocean Pkwy","spellings":["Kensingtn/Ocean Pkwy"],"rows":37,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Kensington","spellings":["Kensington"],"rows":2435,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Kensington / Ocean Pkwy","spellings":["Kensington / Ocean Pkwy"],"rows":11,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Kensington and Parkv","spellings":["Kensington and Parkv"],"rows":13,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Kew Gardens","spellings":["Kew Gardens"],"rows":342,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Kew Gardens Hills","spellings":["Kew Gardens Hills"],"rows":119,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Kinderhook","spellings":["Kinderhook"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Kings Club District","spellings":["Kings Club District"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Kingsbridge","spellings":["Kingsbridge","KINGSBRIDGE"],"rows":423,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Kingsbridge Heights","spellings":["Kingsbridge Heights"],"rows":55,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Kips Bay","spellings":["Kips Bay","KIPSBAY"],"rows":5164,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Koreatown","spellings":["Koreatown"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Laconia","spellings":["Laconia"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Laurelton","spellings":["Laurelton"],"rows":27,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Lefferts","spellings":["Lefferts"],"rows":15,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Lefferts Garden","spellings":["Lefferts Garden"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Lefferts Gardens","spellings":["Lefferts Gardens"],"rows":474,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Lenox Hill","spellings":["Lenox Hill"],"rows":6469,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Lenox Hill-Roosevelt","spellings":["Lenox Hill-Roosevelt"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Lenox Hill-Roosevelt Island","spellings":["Lenox Hill-Roosevelt Island","Lenox Hill-roosevelt Island"],"rows":8,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"LINCOLN","spellings":["LINCOLN"],"rows":160,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Lincoln Center","spellings":["Lincoln Center"],"rows":230,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Lincoln Square","spellings":["Lincoln Square"],"rows":8949,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Lindenwood","spellings":["Lindenwood"],"rows":14,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Little Italy","spellings":["Little Italy"],"rows":962,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Little Neck","spellings":["Little Neck"],"rows":32,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Livingston, Bronx","spellings":["Livingston"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Livingston, Manhattan","spellings":["Livingston"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Livingston, Staten Island","spellings":["Livingston"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"LNGCTY","spellings":["LNGCTY"],"rows":107,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Locust Point","spellings":["Locust Point"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Lodi","spellings":["Lodi"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"LOEAST","spellings":["LOEAST"],"rows":263,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Long Island","spellings":["Long Island"],"rows":6,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Long Island City","spellings":["Long Island City"],"rows":7407,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Longwood","spellings":["Longwood","LONGWOOD"],"rows":45,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Lower East Side","spellings":["Lower East Side"],"rows":8439,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Lower East Side/Chin","spellings":["Lower East Side/Chin"],"rows":78,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Lower East Side/Chinatown","spellings":["Lower East Side/Chinatown"],"rows":9,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Lower Manhattan","spellings":["Lower Manhattan"],"rows":153,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Madison","spellings":["Madison","MADISON"],"rows":54,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Malba","spellings":["Malba"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"MANBEACH","spellings":["MANBEACH"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Manhattan","spellings":["Manhattan","MANHATTAN"],"rows":875,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Manhattan Avenue","spellings":["Manhattan Avenue"],"rows":6,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Manhattan Beach","spellings":["Manhattan Beach"],"rows":90,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Manhattan Terrace","spellings":["Manhattan Terrace"],"rows":9,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Manhattan Valley","spellings":["Manhattan Valley"],"rows":1635,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Manhattanville","spellings":["Manhattanville"],"rows":48,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Manor Heights","spellings":["Manor Heights"],"rows":4,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Mapleton","spellings":["Mapleton","MAPLETON"],"rows":33,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Marble Hill","spellings":["Marble Hill"],"rows":70,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Marine Park","spellings":["Marine Park"],"rows":184,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Marine Park/Mill Basin","spellings":["Marine Park/Mill Basin"],"rows":4,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Marine Pk/Mill Basin","spellings":["Marine Pk/Mill Basin"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Mariners Harbor","spellings":["Mariners Harbor"],"rows":13,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Maspeth","spellings":["Maspeth"],"rows":170,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Meatpacking","spellings":["Meatpacking"],"rows":79,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Meatpacking District","spellings":["Meatpacking District"],"rows":39,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Meiers Corners","spellings":["Meiers Corners"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Melrose","spellings":["Melrose","MELROSE"],"rows":83,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Middle East Side","spellings":["Middle East Side"],"rows":954,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Middle Village","spellings":["Middle Village"],"rows":121,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Middle West Side","spellings":["Middle West Side"],"rows":606,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midland Beach","spellings":["Midland Beach"],"rows":6,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Midtown","spellings":["Midtown","MIDTOWN","midtown"],"rows":4981,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"MIDTOWN [ALL]","spellings":["MIDTOWN [ALL]"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midtown Center","spellings":["Midtown Center"],"rows":33,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midtown Central","spellings":["Midtown Central"],"rows":412,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midtown East","spellings":["Midtown East"],"rows":11944,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Midtown South","spellings":["Midtown South"],"rows":64,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midtown West","spellings":["Midtown West"],"rows":13244,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Midtown West / Hell'","spellings":["Midtown West / Hell'"],"rows":30,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Midwood","spellings":["Midwood","MIDWOOD"],"rows":1677,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Midwood Park","spellings":["Midwood Park"],"rows":3,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Mill Basin","spellings":["Mill Basin"],"rows":64,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Montclair","spellings":["Montclair"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"MORNHGTS","spellings":["MORNHGTS"],"rows":18,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Morningside Heights","spellings":["Morningside Heights"],"rows":2991,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Morris Heights","spellings":["Morris Heights"],"rows":16,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Morris Park","spellings":["Morris Park"],"rows":39,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Morrisania","spellings":["Morrisania"],"rows":62,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Mott Haven","spellings":["Mott Haven","MOTTHAVEN"],"rows":575,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Mount Eden","spellings":["Mount Eden"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Mount Hope","spellings":["Mount Hope"],"rows":26,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"MPARK","spellings":["MPARK"],"rows":4,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"MSPH","spellings":["MSPH"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Mt. Morris Park","spellings":["Mt. Morris Park"],"rows":489,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"MURRAY","spellings":["MURRAY"],"rows":383,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Murray Hill","spellings":["Murray Hill"],"rows":13428,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Murray Hill (QNS)","spellings":["Murray Hill (QNS)"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Murray Hill / Kip's","spellings":["Murray Hill / Kip's"],"rows":78,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Murray Hill / Kips B","spellings":["Murray Hill / Kips B"],"rows":4,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Murray Hill Kips Bay","spellings":["Murray Hill Kips Bay","Murray Hill-kips Bay"],"rows":1999,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"MV","spellings":["MV"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Navy Yard","spellings":["Navy Yard"],"rows":3,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Neponsit","spellings":["Neponsit"],"rows":12,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"New Brighton","spellings":["New Brighton"],"rows":12,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"New Dorp","spellings":["New Dorp"],"rows":24,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"New Dorp Beach","spellings":["New Dorp Beach"],"rows":3,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"New Lots","spellings":["New Lots"],"rows":122,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"New Springville","spellings":["New Springville"],"rows":31,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"NEW UTRECHT","spellings":["NEW UTRECHT"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"New York City","spellings":["New York City"],"rows":23,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"NEW YORK, Brooklyn","spellings":["NEW YORK"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"NEW YORK, Manhattan","spellings":["NEW YORK"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"NoHo","spellings":["Noho","NoHo","NOHO"],"rows":882,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Noho/Central Village","spellings":["Noho/Central Village"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Nolita","spellings":["Nolita","NoLita","NoLIta"],"rows":1096,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"NoMad","spellings":["NoMad","NOMAD","Nomad"],"rows":3471,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"North Corona","spellings":["North Corona"],"rows":13,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"North New York","spellings":["North New York"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"North Riverdale","spellings":["North Riverdale","NORTH RIVERDALE"],"rows":478,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"North Side-south Side","spellings":["North Side-south Side"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"NORTHEAST BRONX","spellings":["NORTHEAST BRONX"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Northeast Flatbush","spellings":["Northeast Flatbush"],"rows":4,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"NORTHWEST BRONX","spellings":["NORTHWEST BRONX"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Norwood","spellings":["Norwood"],"rows":136,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"null, Brooklyn","spellings":["null"],"rows":2029,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"null, Manhattan","spellings":["null"],"rows":1255,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"NYU","spellings":["NYU"],"rows":17,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Oakland Gardens","spellings":["Oakland Gardens"],"rows":34,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Oakwood","spellings":["Oakwood"],"rows":8,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Oakwood Beach","spellings":["Oakwood Beach"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Oakwood Heights","spellings":["Oakwood Heights"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Ocean Hill","spellings":["Ocean Hill"],"rows":414,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Ocean Hill Brownsvil","spellings":["Ocean Hill Brownsvil"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Ocean Hill Brownsville","spellings":["Ocean Hill Brownsville"],"rows":6,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Ocean Parkway","spellings":["Ocean Parkway"],"rows":82,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"OCEANHIL","spellings":["OCEANHIL"],"rows":4,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Old Chatham","spellings":["Old Chatham"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Old Howard Beach","spellings":["Old Howard Beach"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Old Mill Basin","spellings":["Old Mill Basin"],"rows":62,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Olinville","spellings":["Olinville","OLINVILLE"],"rows":5,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"OP","spellings":["OP"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Other Bronx","spellings":["Other Bronx"],"rows":144,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Other Brooklyn","spellings":["Other Brooklyn"],"rows":136,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Other Queens","spellings":["Other Queens"],"rows":148,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"OTHER, Bronx","spellings":["OTHER","Other"],"rows":6,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"OTHER, Brooklyn","spellings":["OTHER","Other"],"rows":21,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"OTHER, Manhattan","spellings":["OTHER","Other"],"rows":17,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"OTHER, Queens","spellings":["OTHER","Other"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Out of Town","spellings":["Out of Town"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Ozone Park","spellings":["Ozone Park"],"rows":45,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Pacific Park","spellings":["Pacific Park"],"rows":231,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Paerdegat Basin","spellings":["Paerdegat Basin"],"rows":15,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Palisades Park","spellings":["Palisades Park"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Park Hill","spellings":["Park Hill"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Park Slope","spellings":["Park Slope"],"rows":18299,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Park Slope South","spellings":["Park Slope South"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Park Slope-gowanus","spellings":["Park Slope-gowanus"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Park Slope/Prospect","spellings":["Park Slope/Prospect"],"rows":141,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Park Slope/Prospect Park","spellings":["Park Slope/Prospect Park"],"rows":9,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Parkchester","spellings":["Parkchester","PARKCHESTER"],"rows":98,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Parkland","spellings":["Parkland"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"PARKSLOP","spellings":["PARKSLOP"],"rows":237,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Pelham Bay","spellings":["Pelham Bay"],"rows":28,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Pelham Gardens","spellings":["Pelham Gardens"],"rows":23,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Pelham Parkway","spellings":["Pelham Parkway"],"rows":76,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Peter Cooper Village","spellings":["Peter Cooper Village"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Pleasant Plains","spellings":["Pleasant Plains"],"rows":3,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Pomonok","spellings":["Pomonok"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Port Morris","spellings":["Port Morris"],"rows":29,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Port Richmond","spellings":["Port Richmond"],"rows":17,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Prince's Bay","spellings":["Prince's Bay"],"rows":11,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"PROSHEI","spellings":["PROSHEI"],"rows":310,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"PROSLEFR","spellings":["PROSLEFR"],"rows":87,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"PROSPARK","spellings":["PROSPARK"],"rows":38,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Heights","spellings":["Prospect Heights"],"rows":4916,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Prospect Hights","spellings":["Prospect Hights"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Leffert Gdn","spellings":["Prospect Leffert Gdn"],"rows":142,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Lefferts","spellings":["Prospect Lefferts"],"rows":6,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Lefferts Ga","spellings":["Prospect Lefferts Ga"],"rows":18,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Lefferts Gardens","spellings":["Prospect Lefferts Gardens"],"rows":1189,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Prospect Lefferts Gardens-Wingate","spellings":["Prospect Lefferts Gardens-Wingate"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Park","spellings":["Prospect Park"],"rows":14,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Prospect Park South","spellings":["Prospect Park South"],"rows":808,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Prospect-Lefferts G","spellings":["Prospect-Lefferts G","Prospect Lefferts G"],"rows":49,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Queens","spellings":["Queens","QUEENS"],"rows":502,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Queens (Other)","spellings":["Queens (Other)"],"rows":312,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Queens Village","spellings":["Queens Village"],"rows":61,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Queensboro Hill","spellings":["Queensboro Hill"],"rows":12,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Ramsen Village","spellings":["Ramsen Village"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Randall Manor","spellings":["Randall Manor"],"rows":8,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"RB","spellings":["RB"],"rows":9,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Red Hook","spellings":["Red Hook","REDHOOK","Redhook","RED HOOK"],"rows":746,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Rego Park","spellings":["Rego Park"],"rows":1325,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Remsen Village","spellings":["Remsen Village"],"rows":36,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"RGWD","spellings":["RGWD"],"rows":17,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"RI","spellings":["RI"],"rows":37,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Richmond Hill","spellings":["Richmond Hill"],"rows":73,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Richmond Hills","spellings":["Richmond Hills"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Richmond Town","spellings":["Richmond Town","Richmondtown","RICHMONDTOWN"],"rows":14,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Richmond Valley","spellings":["Richmond Valley"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Ridgewood","spellings":["Ridgewood"],"rows":1475,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Riverdale","spellings":["Riverdale","RIVERDALE"],"rows":2692,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Rochdale Village","spellings":["Rochdale Village"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Rockaway","spellings":["Rockaway"],"rows":55,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Rockaway All","spellings":["Rockaway All"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Rockaway Beach","spellings":["Rockaway Beach"],"rows":77,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Rockaway Park","spellings":["Rockaway Park"],"rows":212,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Rockwood Park","spellings":["Rockwood Park"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Roosevelt Island","spellings":["Roosevelt Island"],"rows":669,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Rose Hill","spellings":["Rose Hill"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Rosebank","spellings":["Rosebank","ROSEBANK"],"rows":10,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Rosedale","spellings":["Rosedale"],"rows":16,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Rossville","spellings":["Rossville"],"rows":29,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Royal Oak","spellings":["Royal Oak"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"RP","spellings":["RP"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"RWP","spellings":["RWP"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Saint Albans","spellings":["Saint Albans"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Saint George","spellings":["Saint George"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Schuylerville","spellings":["Schuylerville"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Sea Gate","spellings":["Sea Gate","Seagate"],"rows":39,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Seaport District","spellings":["Seaport District"],"rows":189,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Seaside","spellings":["Seaside"],"rows":7,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"SHEEPBAY","spellings":["SHEEPBAY"],"rows":9,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Sheepshead Bay","spellings":["Sheepshead Bay"],"rows":713,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Shore Acres","spellings":["Shore Acres"],"rows":11,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Silver Lake","spellings":["Silver Lake"],"rows":3,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"SoHo","spellings":["Soho","SoHo","SOHO"],"rows":6305,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"SoHo-Nolita","spellings":["SoHo-Nolita","SoHo/Nolita"],"rows":1099,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Somerville","spellings":["Somerville"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Soundview","spellings":["Soundview"],"rows":36,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"South Beach","spellings":["South Beach"],"rows":13,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"South Harlem","spellings":["South Harlem"],"rows":749,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"South Jamaica","spellings":["South Jamaica"],"rows":23,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"South Marlboro","spellings":["South Marlboro"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"South Midwood","spellings":["South Midwood"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"South Ozone Park","spellings":["South Ozone Park"],"rows":28,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"South Richmond Hill","spellings":["South Richmond Hill"],"rows":4,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"South Slope","spellings":["South Slope"],"rows":33,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"South Street Seaport","spellings":["South Street Seaport"],"rows":1796,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"South Village","spellings":["South Village"],"rows":9,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"South Williamsburg","spellings":["South Williamsburg"],"rows":43,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"SOUTHEAST BRONX","spellings":["SOUTHEAST BRONX"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Southold, Brooklyn","spellings":["Southold"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Southold, Manhattan","spellings":["Southold"],"rows":6,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"SOUTHSTSEAPORT","spellings":["SOUTHSTSEAPORT"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Spring Creek","spellings":["Spring Creek"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Springfield Gardens","spellings":["Springfield Gardens"],"rows":15,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Spuyten Duyvil","spellings":["Spuyten Duyvil","SPUYTENDUYVIL"],"rows":738,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"SS","spellings":["SS"],"rows":29,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"St. Albans","spellings":["St. Albans","St Albans"],"rows":39,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"St. George","spellings":["St. George"],"rows":120,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Stapleton","spellings":["Stapleton"],"rows":17,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Stapleton Heights","spellings":["Stapleton Heights"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Starrett City","spellings":["Starrett City"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Staten Island (Othe","spellings":["Staten Island (Othe"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Staten Island, Bronx","spellings":["Staten Island","STATEN ISLAND"],"rows":11,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Staten Island, Brooklyn","spellings":["Staten Island","STATEN ISLAND"],"rows":24,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Staten Island, Manhattan","spellings":["Staten Island","STATEN ISLAND"],"rows":9,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Staten Island, Staten Island","spellings":["Staten Island","STATEN ISLAND"],"rows":30,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Steinway-Ditmars","spellings":["Steinway-Ditmars"],"rows":74,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"STUYHEI","spellings":["STUYHEI"],"rows":5,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Stuyvesant","spellings":["Stuyvesant"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Stuyvesant Heights","spellings":["Stuyvesant Heights"],"rows":1836,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Stuyvesant Town","spellings":["Stuyvesant Town"],"rows":14,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Sugar Hill","spellings":["Sugar Hill"],"rows":10,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Sunnyside","spellings":["Sunnyside","SUNNYSIDE"],"rows":1136,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Sunnyside Gardens","spellings":["Sunnyside Gardens"],"rows":22,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Sunset Park","spellings":["Sunset Park"],"rows":1351,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"SUNSETPK","spellings":["SUNSETPK"],"rows":16,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Sutton","spellings":["Sutton","SUTTON"],"rows":296,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Sutton Area","spellings":["Sutton Area"],"rows":111,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Sutton Place","spellings":["Sutton Place"],"rows":4745,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"The Bronx","spellings":["The Bronx"],"rows":2,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"The Bronx (Other)","spellings":["The Bronx (Other)"],"rows":30,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"The Rockaways","spellings":["The Rockaways"],"rows":5,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Theater District","spellings":["Theater District"],"rows":150,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Throggs Neck","spellings":["Throggs Neck"],"rows":11,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Throgs Neck","spellings":["Throgs Neck","THROGSNECK"],"rows":91,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Times Square Theatre","spellings":["Times Square Theatre"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Todt Hill","spellings":["Todt Hill"],"rows":21,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Tompkinsville","spellings":["Tompkinsville"],"rows":14,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Tottenville","spellings":["Tottenville"],"rows":19,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":true},
  {"label":"Travis","spellings":["Travis"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Tremont","spellings":["Tremont","TREMONT"],"rows":8,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Tribeca","spellings":["Tribeca","TRIBECA","TriBeCa"],"rows":9983,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Tudor City","spellings":["Tudor City"],"rows":942,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"TURTLBAY","spellings":["TURTLBAY"],"rows":167,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Turtle Bay","spellings":["Turtle Bay"],"rows":6385,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Turtle Bay-East Midtown","spellings":["Turtle Bay-East Midtown"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Two Bridges","spellings":["Two Bridges"],"rows":146,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Union Square","spellings":["Union Square"],"rows":654,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Union Square Park","spellings":["Union Square Park"],"rows":21,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Unionport","spellings":["Unionport"],"rows":8,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"University Heights","spellings":["University Heights"],"rows":36,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"UPEAST","spellings":["UPEAST"],"rows":1216,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper Carnegie","spellings":["Upper Carnegie"],"rows":50,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper Carnegie Hill","spellings":["Upper Carnegie Hill"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper East Side","spellings":["Upper East Side","UPPER EAST SIDE"],"rows":52028,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Upper Fifth","spellings":["Upper Fifth"],"rows":15,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper M","spellings":["Upper M"],"rows":30,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper Manhattan","spellings":["Upper Manhattan"],"rows":164,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"UPPER MANHATTAN [ALL","spellings":["UPPER MANHATTAN [ALL","UPPER MANHATTAN [ALL]"],"rows":27,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Upper Saddle River","spellings":["Upper Saddle River"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Upper West Side","spellings":["Upper West Side","UPPER WEST SIDE"],"rows":48377,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Upstate New York","spellings":["Upstate New York"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"UPWEST","spellings":["UPWEST"],"rows":825,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Utopia","spellings":["Utopia"],"rows":3,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Van Nest","spellings":["Van Nest"],"rows":21,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Van Pelt Manor","spellings":["Van Pelt Manor"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Vinegar Hill","spellings":["Vinegar Hill"],"rows":274,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"W. Greenwich Village","spellings":["W. Greenwich Village"],"rows":495,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Wakefield","spellings":["Wakefield","WAKEFIELD"],"rows":55,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Ward Hill","spellings":["Ward Hill"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"WASHHGTS","spellings":["WASHHGTS"],"rows":17,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Washington & Hudson","spellings":["Washington & Hudson"],"rows":52,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Washington & Hudson Heights","spellings":["Washington & Hudson Heights"],"rows":5,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Washington Heights","spellings":["Washington Heights"],"rows":7581,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"Weeksville","spellings":["Weeksville"],"rows":215,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"West 30's","spellings":["West 30's"],"rows":45,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"West 30s - Clinton","spellings":["West 30s - Clinton"],"rows":18,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"West Brighton","spellings":["West Brighton"],"rows":17,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"West Farms","spellings":["West Farms","WESTFARMS"],"rows":22,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"West Harlem","spellings":["West Harlem"],"rows":5141,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"West Harlem & Manhat","spellings":["West Harlem & Manhat"],"rows":22,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"West Midwood","spellings":["West Midwood"],"rows":2,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"West New Brighton","spellings":["West New Brighton"],"rows":1,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"West Side","spellings":["West Side"],"rows":1,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"West Village","spellings":["West Village"],"rows":9557,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"West Village / Green","spellings":["West Village / Green"],"rows":3,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Westchester Square","spellings":["Westchester Square"],"rows":6,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Westchester Village","spellings":["Westchester Village"],"rows":4,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Westerleigh","spellings":["Westerleigh"],"rows":25,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"WESTVILL","spellings":["WESTVILL"],"rows":231,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"WH","spellings":["WH"],"rows":2,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"Whitestone","spellings":["Whitestone"],"rows":69,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"WILLIAMS","spellings":["WILLIAMS"],"rows":220,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Williamsbridge","spellings":["Williamsbridge","WILLIAMSBRIDGE"],"rows":50,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Williamsburg","spellings":["Williamsburg"],"rows":17211,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Williamsburg N Side","spellings":["Williamsburg N Side"],"rows":75,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Williamsburg S Side","spellings":["Williamsburg S Side"],"rows":101,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Williamsburg,North","spellings":["Williamsburg,North"],"rows":7,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Williamsburg,South","spellings":["Williamsburg,South"],"rows":11,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Willowbrook","spellings":["Willowbrook"],"rows":2,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Windor Terrace","spellings":["Windor Terrace"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Windsor Terrace","spellings":["Windsor Terrace"],"rows":2329,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"WINDTERR","spellings":["WINDTERR"],"rows":15,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Wingate","spellings":["Wingate"],"rows":84,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":true},
  {"label":"Woodhaven","spellings":["Woodhaven"],"rows":96,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Woodlawn","spellings":["Woodlawn"],"rows":19,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
  {"label":"Woodlawn Heights","spellings":["Woodlawn Heights"],"rows":12,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"Woodrow","spellings":["Woodrow"],"rows":13,"borough":"StatenIsland","boroughLabel":"Staten Island","offered":false},
  {"label":"Woodside","spellings":["Woodside"],"rows":1100,"borough":"Queens","boroughLabel":"Queens","offered":true},
  {"label":"Woodstock","spellings":["Woodstock"],"rows":9,"borough":"Bronx","boroughLabel":"Bronx","offered":true},
  {"label":"WS","spellings":["WS"],"rows":52,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"WST","spellings":["WST"],"rows":1,"borough":"Queens","boroughLabel":"Queens","offered":false},
  {"label":"X_B_OTHER","spellings":["X_B_OTHER"],"rows":8,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Yonkers, Brooklyn","spellings":["Yonkers"],"rows":1,"borough":"Brooklyn","boroughLabel":"Brooklyn","offered":false},
  {"label":"Yonkers, Manhattan","spellings":["Yonkers"],"rows":2,"borough":"Manhattan","boroughLabel":"Manhattan","offered":false},
  {"label":"Yorkville","spellings":["Yorkville"],"rows":4685,"borough":"Manhattan","boroughLabel":"Manhattan","offered":true},
  {"label":"ZEREGA","spellings":["ZEREGA"],"rows":1,"borough":"Bronx","boroughLabel":"Bronx","offered":false},
]);

const FOLD = (v: string): string => v.toLowerCase().replace(/[^a-z]/g, '');

/** Broker borough labels, for parsing a qualified "Name, Borough" input. */
const BOROUGH_LABEL_FOLDS = new Set(["manhattan","brooklyn","queens","bronx","statenisland","statenisland"]);

/**
 * Split a qualified label into its base name and borough.
 *
 * A QUALIFIED LABEL MUST NOT BE FOLDED WHOLE. `Downtown, Brooklyn` and
 * `Downtown Brooklyn` fold to the same key, so indexing the qualified form made
 * a real neighbourhood collide with the disambiguated form of a different one —
 * and `Downtown Brooklyn` became unsearchable while being offered in the
 * dropdown. The borough suffix is parsed instead of flattened.
 */
function splitQualified(value: string): { base: string; borough: string | null } {
  const comma = value.lastIndexOf(',');
  if (comma === -1) return { base: value, borough: null };
  const tail = value.slice(comma + 1).trim();
  if (!BOROUGH_LABEL_FOLDS.has(FOLD(tail))) return { base: value, borough: null };
  return { base: value.slice(0, comma).trim(), borough: tail };
}

/**
 * Indexed by folded BASE name and by every raw spelling. A key may map to
 * SEVERAL identities — that is what ambiguity looks like, and it must survive.
 */
const BY_FOLDED: ReadonlyMap<string, NeighborhoodIdentity[]> = (() => {
  const m = new Map<string, NeighborhoodIdentity[]>();
  for (const i of NEIGHBORHOOD_IDENTITIES) {
    const keys = [splitQualified(i.label).base, ...i.spellings].map(FOLD);
    for (const key of keys) {
      const list = m.get(key) ?? [];
      if (!list.includes(i)) list.push(i);
      m.set(key, list);
    }
  }
  return m;
})();

/** Every identity a name could mean. Length > 1 means AMBIGUOUS. */
export function identitiesFor(value: unknown): readonly NeighborhoodIdentity[] {
  if (typeof value !== 'string') return [];
  return BY_FOLDED.get(FOLD(splitQualified(value.trim()).base)) ?? [];
}

/**
 * The identity a typed, stored or polygon name means.
 *
 * `borough` disambiguates. Without it an ambiguous name returns null rather than
 * silently picking one — choosing between Bay Terrace in Queens and Bay Terrace
 * in Staten Island is exactly the quiet substitution this contract prevents.
 */
export function identityFor(value: unknown, borough?: string | null): NeighborhoodIdentity | null {
  if (typeof value !== 'string') return null;
  const parsed = splitQualified(value.trim());
  const hits = identitiesFor(value);
  if (hits.length === 0) return null;
  if (hits.length === 1) return hits[0];
  borough = borough ?? parsed.borough;
  if (!borough) return null;
  const want = FOLD(borough);
  return hits.find((h) => FOLD(h.borough) === want || FOLD(h.boroughLabel) === want) ?? null;
}

/** The borough a neighbourhood belongs to, as the PROVIDER value. */
export function boroughForNeighborhood(value: unknown, borough?: string | null): string | null {
  return identityFor(value, borough)?.borough ?? null;
}

/** Every raw Cotality spelling to search for a selection. */
export function spellingsFor(value: unknown, borough?: string | null): readonly string[] {
  return identityFor(value, borough)?.spellings ?? [];
}

/** BACK-COMPAT: raw spelling -> row count. */
export const SUBDIVISION_NAME_LIVE: Readonly<Record<string, number>> = Object.freeze(
  Object.fromEntries(
    NEIGHBORHOOD_IDENTITIES.flatMap((i) => i.spellings.map((s) => [s, i.rows])),
  ),
);

export const NEIGHBORHOOD_VOCABULARY_PROBED_AT = "2026-08-31" as const;
export const NEIGHBORHOOD_VOCABULARY_ROWS_READ = 591409 as const;
