/**
 * GENERATED — do not edit. `node scripts/search/generate-subdivision-vocabulary.mjs`
 *
 * The SubdivisionName values the LIVE Cotality feed carries across the
 * Search-eligible universe (Residential + ResidentialLease, Active +
 * ComingSoon + ActiveUnderContract), read exhaustively — 7770 rows,
 * 8 pages, not truncated — on 2026-08-31.
 *
 * This is the PROVIDER vocabulary, not a Mallan naming decision. A neighbourhood
 * search emits only values from this list, so every term is one the feed
 * actually carries: identity, never an asserted equivalence.
 *
 * Evidence: artifacts/section5-closure-probe-2026-08-31.json
 */

/** Live value -> row count observed at generation time. */
export const SUBDIVISION_NAME_LIVE: Readonly<Record<string, number>> = Object.freeze({
  "Alphabet City": 2,
  "Annadale": 2,
  "Arverne": 1,
  "Astoria": 88,
  "Astoria Heights": 1,
  "Bath Beach": 1,
  "Battery Park City": 88,
  "Bay Ridge": 44,
  "Bay Terrace": 2,
  "Baychester": 1,
  "Bayside": 2,
  "Bayswater": 1,
  "Bedford Park": 2,
  "Bedford-Stuyvesant": 101,
  "Beekman": 37,
  "Belle Harbor": 5,
  "Bellerose": 4,
  "Belmont": 1,
  "Bensonhurst": 2,
  "Bergen Beach": 1,
  "Boerum Hill": 30,
  "Borough Park": 2,
  "Breezy Point": 3,
  "Briarwood": 1,
  "Brighton Beach": 24,
  "Broad Channel": 1,
  "Bronxdale": 3,
  "Bronxwood": 1,
  "Brooklyn Heights": 52,
  "Brownsville": 10,
  "Bushwick": 109,
  "Canarsie": 27,
  "Carnegie Hill": 77,
  "Carroll Gardens": 28,
  "Castleton Corners": 1,
  "Central Harlem": 93,
  "Central Park South": 106,
  "Central Riverdale": 39,
  "Chelsea": 219,
  "Chinatown": 23,
  "City Island": 2,
  "City Line": 3,
  "Clason Point": 1,
  "Clinton Hill": 45,
  "Cobble Hill": 10,
  "College Point": 1,
  "Columbia Street Waterfront": 3,
  "Concord": 1,
  "Concourse": 11,
  "Concourse Village": 18,
  "Coney Island": 6,
  "Country Club": 1,
  "Crown Heights": 83,
  "Cypress Hills": 5,
  "Ditmars Steinway": 41,
  "Ditmas Park": 27,
  "Douglaston": 5,
  "Downtown Brooklyn": 88,
  "Dumbo": 27,
  "DUMBO": 16,
  "Dyker Heights": 2,
  "East Elmhurst": 1,
  "East Flatbush": 30,
  "East Harlem": 72,
  "East Morrisania": 1,
  "East New York": 18,
  "East Village": 71,
  "East Williamsburg": 15,
  "Eastchester": 1,
  "Edgemere": 1,
  "Elmhurst": 16,
  "Eltingville": 1,
  "Estate Area": 3,
  "Farragut": 2,
  "Fieldston": 8,
  "Financial District": 202,
  "Flatbush": 49,
  "Flatiron": 89,
  "Flatlands": 7,
  "Flushing": 38,
  "Fordham": 9,
  "Forest Hills": 61,
  "Fort George": 3,
  "Fort Greene": 25,
  "Fort Hamilton": 17,
  "Gerritsen Beach": 2,
  "Glen Oaks": 2,
  "Glendale": 6,
  "Gowanus": 75,
  "Gramercy Park": 112,
  "Grasmere": 1,
  "Gravesend": 8,
  "Great Kills": 2,
  "Greenpoint": 82,
  "Greenwich Village": 118,
  "Greenwood Heights": 28,
  "Hamilton Heights": 50,
  "Harlem": 54,
  "Hell's Kitchen": 221,
  "Highbridge": 2,
  "Hollis": 2,
  "Homecrest": 6,
  "Howard Beach": 1,
  "Hudson Heights": 47,
  "Hudson Square": 29,
  "Hudson Yards": 70,
  "Hunters Point": 14,
  "Inwood": 26,
  "Jackson Heights": 51,
  "Jamaica": 36,
  "Jamaica Estates": 4,
  "Jamaica Hills": 1,
  "Kensington": 36,
  "Kew Gardens": 4,
  "Kew Gardens Hills": 6,
  "Kingsbridge": 7,
  "Kingsbridge Heights": 2,
  "Kips Bay": 115,
  "Lenox Hill": 422,
  "Lincoln Square": 246,
  "Lindenwood": 2,
  "Little Italy": 7,
  "Little Neck": 2,
  "Locust Point": 1,
  "Long Island City": 153,
  "Longwood": 1,
  "Lower East Side": 110,
  "Madison": 8,
  "Manhattan Beach": 4,
  "Manhattan Valley": 21,
  "Manhattanville": 3,
  "Mapleton": 1,
  "Marble Hill": 1,
  "Marine Park": 5,
  "Mariners Harbor": 1,
  "Maspeth": 4,
  "Meiers Corners": 1,
  "Melrose": 2,
  "Middle Village": 4,
  "Midland Beach": 1,
  "midtown": 1,
  "Midtown": 200,
  "Midtown East": 192,
  "Midtown West": 63,
  "Midwood": 33,
  "Mill Basin": 5,
  "Morningside Heights": 49,
  "Morris Heights": 4,
  "Morris Park": 1,
  "Morrisania": 1,
  "Mott Haven": 3,
  "Mount Hope": 1,
  "Murray Hill": 210,
  "New Lots": 6,
  "New Springville": 1,
  "Noho": 2,
  "NoHo": 17,
  "Nolita": 10,
  "NoLIta": 2,
  "NoMad": 65,
  "NOMAD": 1,
  "North Corona": 1,
  "North Riverdale": 29,
  "Norwood": 6,
  "Oakland Gardens": 2,
  "Ocean Hill": 12,
  "Ocean Parkway": 1,
  "Park Slope": 62,
  "Parkchester": 2,
  "Pelham Bay": 1,
  "Pelham Gardens": 1,
  "Pelham Parkway": 1,
  "Pleasant Plains": 1,
  "Port Morris": 1,
  "Port Richmond": 1,
  "Prince's Bay": 1,
  "Prospect Heights": 19,
  "Prospect Lefferts Gardens": 29,
  "Prospect Park South": 17,
  "Queens Village": 5,
  "Red Hook": 8,
  "Rego Park": 20,
  "Richmond Hill": 3,
  "Ridgewood": 16,
  "Riverdale": 23,
  "Rochdale Village": 2,
  "Rockaway Beach": 4,
  "Rockaway Park": 11,
  "Roosevelt Island": 24,
  "Rose Hill": 1,
  "Rosebank": 1,
  "Rosedale": 2,
  "Seaside": 1,
  "Sheepshead Bay": 21,
  "Soho": 6,
  "SoHo": 48,
  "SOHO": 1,
  "Soundview": 2,
  "South Harlem": 45,
  "South Jamaica": 3,
  "South Ozone Park": 2,
  "South Street Seaport": 30,
  "Springfield Gardens": 1,
  "Spuyten Duyvil": 75,
  "St. Albans": 1,
  "St. George": 8,
  "Stapleton": 1,
  "Stuyvesant Heights": 67,
  "Sunnyside": 17,
  "Sunnyside Gardens": 1,
  "Sunset Park": 5,
  "Sutton Place": 181,
  "Throgs Neck": 2,
  "Todt Hill": 3,
  "Tompkinsville": 1,
  "Tottenville": 1,
  "Tribeca": 127,
  "TriBeCa": 6,
  "Tudor City": 2,
  "Turtle Bay": 123,
  "Two Bridges": 20,
  "University Heights": 2,
  "Upper East Side": 226,
  "Upper West Side": 366,
  "Van Nest": 1,
  "Vinegar Hill": 3,
  "Wakefield": 2,
  "Washington Heights": 50,
  "Weeksville": 16,
  "West Harlem": 28,
  "West Village": 89,
  "Whitestone": 5,
  "Williamsburg": 191,
  "Windsor Terrace": 17,
  "Wingate": 6,
  "Woodhaven": 3,
  "Woodlawn Heights": 2,
  "Woodside": 38,
  "Woodstock": 1,
  "Yorkville": 158,
});

/** ISO date the vocabulary was read from live Cotality. */
export const SUBDIVISION_VOCABULARY_PROBED_AT = "2026-08-31" as const;

/** Rows read in the exhaustive pass that produced this list. */
export const SUBDIVISION_VOCABULARY_ROWS_READ = 7770 as const;

