-- Reproducible red→green proof for the 2026-07-14 contact-capture hotfix.
--
-- The bug: atomicMergeUpsertLead() ran `INSERT INTO "Lead"` (quoted, case-
-- sensitive) but Prisma maps the model to the physical table `leads`
-- (@@map("leads")). The quoted relation "Lead" does not exist, so every fresh
-- /api/contact insert threw 42P01 undefined_table and the lead was dropped.
--
-- Run against a DISPOSABLE Postgres (never production). Local harness:
--   initdb -D "$D" -U postgres -A trust
--   pg_ctl -D "$D" -o "-p 55432" -w start
--   psql -h localhost -p 55432 -U postgres -d postgres -f scripts/verify-contact-capture.sql
--   pg_ctl -D "$D" -w stop && rm -rf "$D"

-- leads table mirroring production's constrained columns. The ONLY NOT-NULL/
-- no-default columns on prod leads are email, first_name, last_name, phone,
-- updated_at (all supplied by the INSERT); seller_potential_reason /
-- building_type_pref are nullable (so omitting them is safe — the old
-- OPS-001 NOT-NULL theory was disproven live).
DROP TABLE IF EXISTS leads;
CREATE TABLE leads (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name               text NOT NULL,
  last_name                text NOT NULL,
  email                    text NOT NULL UNIQUE,
  phone                    text NOT NULL,
  roles                    text[],
  status                   text NOT NULL DEFAULT 'new',
  source                   text NOT NULL DEFAULT 'website',
  consent_captured_at      timestamp,
  seller_potential_reason  text[],
  building_type_pref       text[],
  created_at               timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               timestamp NOT NULL
);

\echo '--- RED: the OLD statement (must fail with 42P01 undefined_table) ---'
-- EXPECTED: ERROR: relation "Lead" does not exist
INSERT INTO "Lead" ("email") VALUES ('red@example.com');

\echo '--- GREEN 1: new email creates one row ---'
INSERT INTO "leads" AS existing (
  "first_name","last_name","email","phone","roles",
  "status","source","consent_captured_at","created_at","updated_at"
) VALUES (
  'Jane','Doe','jane@example.com','555-1000', ARRAY['buyer']::text[],
  'new','contact_form','2026-07-14T00:00:00', NOW(), NOW()
)
ON CONFLICT ("email") DO UPDATE SET
  "phone" = COALESCE(NULLIF(EXCLUDED."phone", ''), existing."phone"),
  "roles" = ARRAY(SELECT DISTINCT role FROM unnest(existing."roles" || EXCLUDED."roles") AS role WHERE role <> ''),
  "consent_captured_at" = EXCLUDED."consent_captured_at",
  "updated_at" = NOW()
RETURNING "id","roles";

\echo '--- GREEN 2: same email, +seller, BLANK phone, new consent ---'
INSERT INTO "leads" AS existing (
  "first_name","last_name","email","phone","roles",
  "status","source","consent_captured_at","created_at","updated_at"
) VALUES (
  'Jane','Doe','jane@example.com','', ARRAY['seller']::text[],
  'new','contact_form','2026-07-15T00:00:00', NOW(), NOW()
)
ON CONFLICT ("email") DO UPDATE SET
  "phone" = COALESCE(NULLIF(EXCLUDED."phone", ''), existing."phone"),
  "roles" = ARRAY(SELECT DISTINCT role FROM unnest(existing."roles" || EXCLUDED."roles") AS role WHERE role <> ''),
  "consent_captured_at" = EXCLUDED."consent_captured_at",
  "updated_at" = NOW()
RETURNING "id","roles";

\echo '--- ASSERTIONS (expect: 1 row | {buyer,seller} | 555-1000 | 2026-07-15) ---'
SELECT count(*) AS rows_expect_1 FROM leads;
SELECT roles AS roles_expect_buyer_seller, phone AS phone_expect_555_1000,
       consent_captured_at AS consent_expect_07_15
FROM leads WHERE email = 'jane@example.com';
