/**
 * SEARCH CONTRACT — the executor's executable parameters and vocabularies, as ONE payload
 * for browser consumers (PURE; zero vocabulary or business logic of its own).
 *
 * Chain (Search Consolidation Packet 1, 2026-09-05):
 *   data/cotality-enums.live.json  (regenerated by `npm run cotality:pull <ISO date>`, drift-checked
 *                                    by `npm run cotality:verify`)
 *   → lib/search/canonical/live-truth.ts  (typed projection, test-bound to the file)
 *   → lib/search/engine/criteria.ts       (the executor — imports every member list from live-truth)
 *   → THIS module → GET /api/idx/search/contract → the CRM shell.
 *
 * The browser must never carry a hand-maintained copy of these lists.
 */

import { LIVE_AUTHORITY } from '../canonical/live-truth';
import {
  EXECUTED_PARAMS, STANDARD_STATUS_MEMBERS, PROPERTY_TYPE_MEMBERS, COMMON_INTEREST_MEMBERS,
  STRUCTURE_TYPE_MEMBERS, CITY_REGION_VALUES, DEFAULT_SORT, DEFAULT_PAGE, MAX_PAGE, type Member,
} from './criteria';

export interface ContractMember { token: string; label: string }
export interface SearchContract {
  version: 1;
  vocabularyPulledAt: string;
  executableParams: string[];
  members: {
    StandardStatus: ContractMember[];
    PropertyType: ContractMember[];
    CommonInterest: ContractMember[];
    StructureType: ContractMember[];
  };
  cityRegion: string[];
  sortKeys: string[];
  defaultSort: string;
  defaultPage: number;
  maxPage: number;
}

const toMembers = (m: readonly Member[]): ContractMember[] => m.map(([token, label]) => ({ token, label }));

export function searchContract(): SearchContract {
  return {
    version: 1,
    vocabularyPulledAt: LIVE_AUTHORITY.verifiedAgainstPull,
    executableParams: [...EXECUTED_PARAMS].sort(),
    members: {
      StandardStatus: toMembers(STANDARD_STATUS_MEMBERS),
      PropertyType: toMembers(PROPERTY_TYPE_MEMBERS),
      CommonInterest: toMembers(COMMON_INTEREST_MEMBERS),
      StructureType: toMembers(STRUCTURE_TYPE_MEMBERS),
    },
    cityRegion: [...CITY_REGION_VALUES],
    sortKeys: ['price_desc', 'price_asc', 'newest'],
    defaultSort: DEFAULT_SORT,
    defaultPage: DEFAULT_PAGE,
    maxPage: MAX_PAGE,
  };
}
