import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

type Status = 'PASS' | 'YELLOW' | 'FAIL';
type Check = { code: string; name: string; status: Status; details: string };
const root = process.cwd();
const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
const outDir = path.join(root, 'ops', 'audit', 'sentinel-g');
const checks: Check[] = [];
const required = ['CLAUDE.md','docs/architecture/REPO-SOURCE-OF-TRUTH-CHARTER.md','docs/compliance/COMPLIANCE-CANONICAL-INDEX.md','docs/agents/SENTINEL-G-MANDATE-2026-05-28.md','lib/idx/fetch.ts','lib/idx/trestle-mapper.ts','lib/idx/public-dto.ts','lib/idx/db-to-public-dto.ts','lib/listing-slug.ts','app/api/listings/route.ts','app/api/listings/[id]/route.ts','app/api/listings/suggest/route.ts','app/listing/[...slug]/page.tsx','lib/search/public-listing-db.ts','lib/search/public-listing-trestle.ts','data/rebny-rls-property-fields.csv','data/RLS-FIELD-REGISTRY.md','artifacts/metadata.xml'];
const forbidden = ['PrivateRemarks','PrivateOfficeRemarks','ShowingInstructions','ShowingContactPhone','ShowingContactName','ShowingRequirements','LockBoxType','LockBoxLocation','ListAgentEmail','ListAgentDirectPhone','ListAgentMlsId','CoListAgentEmail','CoListAgentDirectPhone','owner_client_id','sellerEmail','sellerPhone','seller_email','seller_phone'];
const r = (f:string)=>path.join(root,f);
const exists = (f:string)=>fs.existsSync(r(f));
const read = (f:string)=>fs.readFileSync(r(f),'utf8');
const uniq = <T,>(x:T[])=>[...new Set(x)];
const add = (code:string,name:string,status:Status,details:string)=>checks.push({code,name,status,details});
const miss = (c:string,n:string[])=>n.filter(x=>!c.includes(x));
const set = (x:string[])=>new Set(x.map(s=>s.trim()).filter(Boolean));
const sample = (x:string[],n=25)=>x.slice(0,n).join(', ')+(x.length>n?` ... +${x.length-n} more`:'');
const overall = ():Status=>checks.some(c=>c.status==='FAIL')?'FAIL':checks.some(c=>c.status==='YELLOW')?'YELLOW':'PASS';
const stripComments = (s:string)=>s.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'');
const lits = (block:string)=>uniq([...stripComments(block).matchAll(/["']([A-Za-z0-9_]+)["']/g)].map(m=>m[1]));
function bFields(mapper:string){const out:string[]=[]; for(const m of mapper.matchAll(/const\s+B[A-Z0-9_]+\s*=\s*\[([\s\S]*?)\];/g)) out.push(...lits(m[1])); return uniq(out)}
function excluded(mapper:string){const m=mapper.match(/IDX_PLUS_EXCLUDED_FIELDS\s*=\s*new\s+Set\s*\(\s*\[([\s\S]*?)\]\s*\)/); return m?lits(m[1]):[]}
function renames(mapper:string){const m=mapper.match(/RESO_TO_RLS_RENAMES[^{]*\{([\s\S]*?)\};/); const out:Record<string,string>={}; if(!m)return out; for(const row of stripComments(m[1]).matchAll(/([A-Za-z0-9_]+)\s*:\s*["']([A-Za-z0-9_]+)["']/g)) out[row[1]]=row[2]; return out}
function metaFields(xml:string){if(!xml)return[]; const m=xml.match(/<EntityType\s+Name=["']Property["'][^>]*>([\s\S]*?)<\/EntityType>/); const scope=m?m[1]:xml; return uniq([...scope.matchAll(/<Property\s+Name=["']([^"']+)["']/g)].map(x=>x[1]))}
function csvFields(csv:string){const out:string[]=[]; for(const line of csv.split(/\r?\n/).slice(1)){ if(!line.trim())continue; const cells=line.split(',').map(c=>c.trim().replace(/^"|"$/g,'')); if(cells[1])out.push(cells[1]); if(cells[3])out.push(cells[3]); } return uniq(out)}
function mdFields(md:string){const allowed=(md.split('### Fields NOT on Trestle')[0]||md); return uniq([...allowed.matchAll(/`([A-Za-z0-9_]+)`/g)].map(m=>m[1]))}
function iface(src:string,name:string){const s=src.indexOf(`export interface ${name}`); if(s<0)return''; const o=src.indexOf('{',s); let d=0; for(let i=o;i<src.length;i++){if(src[i]==='{')d++; if(src[i]==='}')d--; if(d===0)return src.slice(o+1,i)} return''}
async function probe(base:string,part:string){const res=await fetch(`${base.replace(/\/$/,'')}${part}`,{redirect:'manual'}); return {status:res.status,body:await res.text().catch(()=>''),location:res.headers.get('location')||''}}
async function main(){
 const missingFiles=required.filter(f=>!exists(f)); add('G-000','Required Sentinel-G source files exist',missingFiles.length?'FAIL':'PASS',missingFiles.length?`Missing: ${missingFiles.join(', ')}`:`${required.length} required files found.`);
 const mapper=exists('lib/idx/trestle-mapper.ts')?read('lib/idx/trestle-mapper.ts'):''; const publicDto=exists('lib/idx/public-dto.ts')?read('lib/idx/public-dto.ts'):''; const dbDto=exists('lib/idx/db-to-public-dto.ts')?read('lib/idx/db-to-public-dto.ts'):''; const fetchTs=exists('lib/idx/fetch.ts')?read('lib/idx/fetch.ts'):''; const suggest=exists('app/api/listings/suggest/route.ts')?read('app/api/listings/suggest/route.ts'):''; const listingRoute=exists('app/api/listings/route.ts')?read('app/api/listings/route.ts'):''; const apiDetail=exists('app/api/listings/[id]/route.ts')?read('app/api/listings/[id]/route.ts'):''; const pageDetail=exists('app/listing/[...slug]/page.tsx')?read('app/listing/[...slug]/page.tsx'):''; const slug=exists('lib/listing-slug.ts')?read('lib/listing-slug.ts'):''; const idxCsv=exists('data/rebny-rls-property-fields.csv')?read('data/rebny-rls-property-fields.csv'):''; const registryMd=exists('data/RLS-FIELD-REGISTRY.md')?read('data/RLS-FIELD-REGISTRY.md'):''; const metadata=exists('artifacts/metadata.xml')?read('artifacts/metadata.xml'):'';
 const all=bFields(mapper), exc=excluded(mapper), excSet=set(exc), selected=all.filter(f=>!excSet.has(f)), rn=renames(mapper); const meta=metaFields(metadata), metaSet=set(meta), registry=uniq([...csvFields(idxCsv),...mdFields(registryMd)]), registrySet=set(registry); const hash=metadata?crypto.createHash('sha256').update(metadata).digest('hex'):null;
 const m1=miss(mapper,['RESO_TO_RLS_RENAMES','IDX_PLUS_SELECT_FIELDS','computeGateColumns','InternetEntireListingDisplayYN','InternetAddressDisplayYN','Permission']); add('G-001','Mapper exposes required contract primitives',m1.length?'FAIL':'PASS',m1.length?`Missing anchors: ${m1.join(', ')}`:`Found ${all.length} B-category fields, ${exc.length} exclusions, ${selected.length} selected fields.`);
 const badExc=selected.filter(f=>excSet.has(f)); add('G-002','Excluded IDX Plus fields are not selected',badExc.length?'FAIL':'PASS',badExc.length?`Excluded fields still selected: ${sample(badExc)}`:`${exc.length} excluded fields absent from selected set.`);
 add('G-003','Provider metadata mode','PASS','Static normalized IDX Plus Web API registry mode. Set up separate live provider job only when credentials are available.');
 add('G-004','Metadata and normalized IDX Plus registry are readable',meta.length&&registry.length?'PASS':'FAIL',`${meta.length} Property metadata fields parsed. ${registry.length} normalized IDX Plus registry fields parsed. sha256=${hash}`);
 const unresolved=selected.filter(f=>{const rr=rn[f]; return !metaSet.has(f)&&!(rr&&metaSet.has(rr))&&!registrySet.has(f)&&!(rr&&registrySet.has(rr))}); add('G-005','Selected fields exist in metadata or normalized IDX Plus registry after rename resolution',unresolved.length?'FAIL':'PASS',unresolved.length?`${unresolved.length} selected fields missing after metadata/registry/rename resolution: ${sample(unresolved)}`:`${selected.length} selected fields validated against Property metadata, normalized IDX Plus registry, or rename target.`);
 const badRn=Object.entries(rn).filter(([s,d])=>!s||!d||s===d); add('G-006','RESO_TO_RLS_RENAMES has valid shape',badRn.length?'FAIL':'PASS',badRn.length?`Bad rename rows: ${sample(badRn.map(([s,d])=>`${s}->${d}`))}`:`${Object.keys(rn).length} rename rows have valid shape.`);
 const idMissing=['ListingId','ListingKey','SourceSystemKey','OriginatingSystemKey','ListingKeyNumeric'].filter(f=>!all.includes(f)&&!metaSet.has(f)&&!registrySet.has(f)&&!(rn[f]&&(metaSet.has(rn[f])||registrySet.has(rn[f])))); const fetchMiss=miss(fetchTs,['ListingId eq','fetchSingleListing','ListingId != entity key']); add('G-007','Provider ID chain fields and fetch semantics are present',idMissing.length||fetchMiss.length?'FAIL':'PASS',idMissing.length||fetchMiss.length?`Missing ID fields/anchors: ${sample([...idMissing,...fetchMiss])}`:'Provider ID chain and ListingId fetch semantics found.');
 const dto=iface(publicDto,'PublicListingDTO'); const dtoLeaks=forbidden.filter(k=>new RegExp(`\\b${k}\\b`).test(dto)); const dtoMiss=miss(publicDto,['_displayCompliance','requiresAttribution','attributionText','disclaimerRequired','isAddressDisplayable','generateListingSlug']); add('G-008','Public DTO has attribution/canonical fields and no internal fields in DTO shape',dtoLeaks.length||dtoMiss.length?'FAIL':'PASS',dtoLeaks.length||dtoMiss.length?`DTO leaks=${dtoLeaks.join(', ')||'none'} missing=${dtoMiss.join(', ')||'none'}`:'Public DTO shape is clean.');
 const dbMiss=miss(dbDto,['classifyDbListing','mallan-exclusive','third-party-idx','website-only','filterDisplayableDbListings','owner_client_id','agent_id','rls_eligible']); add('G-009','DB DTO classifies Mallan exclusive vs third-party IDX vs website-only',dbMiss.length?'FAIL':'PASS',dbMiss.length?`Missing DB classification anchors: ${dbMiss.join(', ')}`:'DB provenance classifier anchors found.');
 const gateMiss=miss(mapper+dbDto+suggest+listingRoute,['computeGateColumns','filterDisplayableDbListings','checkDistributionGates','InternetEntireListingDisplayYN','InternetAddressDisplayYN','owner_opt_out','participant_only']); add('G-010','Display gates are represented across mapper, DB DTO, suggest, and listing route',gateMiss.length?'FAIL':'PASS',gateMiss.length?`Missing gate anchors: ${gateMiss.join(', ')}`:'Display gate anchors found across layers.');
 const sugMiss=miss(suggest,['SUGGEST_SELECT_FIELDS','ListingId','ListingKey','checkDistributionGates','isAddressDisplayablePerSuggest','InternetAddressDisplayYN','InternetEntireListingDisplayYN']); const sugLeaks=forbidden.filter(k=>new RegExp(`\\b${k}\\b`).test(suggest)); add('G-011','Public suggest route uses identity/gate anchors and avoids private fields',sugMiss.length||sugLeaks.length?'FAIL':'PASS',sugMiss.length||sugLeaks.length?`suggest missing=${sugMiss.join(', ')||'none'} private-key-presence=${sugLeaks.join(', ')||'none'}`:'Suggest route identity/gate anchors clean.');
 const slugMiss=miss(slug,['generateListingSlug','extractListingIdFromSlug','extractMlsIdFromSlug','isMlsIdSlug','internetAddressDisplayYN','listing-']); const pageMiss=miss(pageDetail,['extractListingIdFromSlug','extractMlsIdFromSlug','parseAddressSlug','generateListingSlug']); add('G-012','Public detail page supports canonical address slug plus fallback ID resolution',slugMiss.length||pageMiss.length?'FAIL':'PASS',slugMiss.length||pageMiss.length?`slug missing=${slugMiss.join(', ')||'none'} page missing=${pageMiss.join(', ')||'none'}`:'Slug helper and public detail page anchors found.');
 const routeMiss=miss(listingRoute,['filterDisplayableDbListings','annotateCoListedSiblings']); add('G-013','Public listing route applies display filtering and sibling annotation',routeMiss.length?'FAIL':'PASS',routeMiss.length?`Missing listing route anchors: ${routeMiss.join(', ')}`:'Public listing route anchors found.');
 const apiMiss=miss(apiDetail,['fetchSingleListing','checkDistributionGates','toPublicDTO']); add('G-014','Public API detail route remains ID-oriented while page route handles slugs',apiMiss.length?'FAIL':'PASS',apiMiss.length?`Missing API detail route anchors: ${apiMiss.join(', ')}`:'API route validated separately from page slug route.');
 const base=process.env.SENTINEL_G_BASE_URL||process.env.NEXT_PUBLIC_SITE_URL||''; if(base){for(const q of ['/api/listings/suggest?q=SL-0004','/api/listings/suggest?q=333%20E%2046','/api/listings?address=333%20E%2046','/listing/sl-0004']){try{const pr=await probe(base,q); const leaks=forbidden.filter(k=>pr.body.includes(k)); const fallbackShown=q!=='/listing/sl-0004'&&pr.body.includes('/listing/sl-0004'); const ok=q==='/listing/sl-0004'?[200,301,302,307,308,404].includes(pr.status):pr.status<500; add('G-015',`Public endpoint probe ${q}`,leaks.length||fallbackShown||!ok?'FAIL':'PASS',`status=${pr.status}${pr.location?` location=${pr.location}`:''}${leaks.length?` leaks=${leaks.join(',')}`:''}${fallbackShown?' fallback-url-displayed=true':''}`)}catch(e){add('G-015',`Public endpoint probe ${q}`,'FAIL',e instanceof Error?e.message:String(e))}}} else add('G-015','Public endpoint probes','PASS','Endpoint probes not configured in this run. Set SENTINEL_G_BASE_URL for production URL proof.');
 const report={tool:'Sentinel-G' as const,status:overall(),generatedAt:new Date().toISOString(),mode:'static-normalized-idx-plus',metadataHash:hash,selectedFieldCount:selected.length,metadataPropertyFieldCount:meta.length,idxRegistryFieldCount:registry.length,checks}; fs.mkdirSync(outDir,{recursive:true}); const jp=path.join(outDir,`${stamp}-report.json`), mp=path.join(outDir,`${stamp}-report.md`); fs.writeFileSync(jp,JSON.stringify(report,null,2)); fs.writeFileSync(mp,`# Sentinel-G Report\n\nStatus: **${report.status}**\n\nGenerated: ${report.generatedAt}\n\nMode: ${report.mode}\n\nSelected fields: ${report.selectedFieldCount}\n\nMetadata Property fields: ${report.metadataPropertyFieldCount}\n\nNormalized IDX Plus registry fields: ${report.idxRegistryFieldCount}\n\n| Code | Status | Check | Details |\n|---|---|---|---|\n${checks.map(c=>`| ${c.code} | ${c.status} | ${c.name} | ${c.details.replace(/\|/g,'\\|')} |`).join('\n')}\n`); console.log(`Sentinel-G status: ${report.status}`); console.log(`Mode: ${report.mode}`); console.log(`JSON report: ${path.relative(root,jp)}`); console.log(`Markdown report: ${path.relative(root,mp)}`); for(const c of checks) console.log(`${c.status.padEnd(6)} ${c.code} ${c.name}`); if(report.status==='FAIL')process.exit(1);
}
main().catch(e=>{add('G-999','Sentinel-G runner crashed','FAIL',e instanceof Error?(e.stack||e.message):String(e)); fs.mkdirSync(outDir,{recursive:true}); fs.writeFileSync(path.join(outDir,`${stamp}-report.json`),JSON.stringify({tool:'Sentinel-G',status:'FAIL',generatedAt:new Date().toISOString(),mode:'crashed',checks},null,2)); console.error(e); process.exit(1)});
