import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

type Status = 'PASS' | 'YELLOW' | 'FAIL';
type Check = { code: string; name: string; status: Status; details: string };
const root = process.cwd();
const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
const outDir = path.join(root, 'ops', 'audit', 'sentinel-g');
const checks: Check[] = [];
const required = ['CLAUDE.md','docs/architecture/REPO-SOURCE-OF-TRUTH-CHARTER.md','docs/compliance/COMPLIANCE-CANONICAL-INDEX.md','docs/agents/SENTINEL-G-MANDATE-2026-05-28.md','lib/idx/auth.ts','lib/idx/fetch.ts','lib/idx/trestle-mapper.ts','lib/idx/public-dto.ts','lib/idx/db-to-public-dto.ts','lib/listing-slug.ts','app/api/listings/route.ts','app/api/listings/[id]/route.ts','app/api/listings/suggest/route.ts','app/listing/[id]/page.tsx','lib/search/public-listing-db.ts','lib/search/public-listing-trestle.ts','data/rebny-rls-property-fields.csv','data/rebny-rls-property-lookup.csv','data/RLS-FIELD-REGISTRY.md','artifacts/metadata.xml'];
const forbidden = ['PrivateRemarks','PrivateOfficeRemarks','ShowingInstructions','ShowingContactPhone','ShowingContactName','ShowingRequirements','LockBoxType','LockBoxLocation','ListAgentEmail','ListAgentDirectPhone','ListAgentMlsId','CoListAgentEmail','CoListAgentDirectPhone','owner_client_id','sellerEmail','sellerPhone','seller_email','seller_phone'];
function p(f:string){return path.join(root,f)}
function exists(f:string){return fs.existsSync(p(f))}
function read(f:string){return fs.readFileSync(p(f),'utf8')}
function uniq<T>(x:T[]){return [...new Set(x)]}
function add(code:string,name:string,status:Status,details:string){checks.push({code,name,status,details})}
function miss(c:string,n:string[]){return n.filter(x=>!c.includes(x))}
function set(x:string[]){return new Set(x.map(s=>s.trim()).filter(Boolean))}
function sample(x:string[],n=25){return x.slice(0,n).join(', ')+(x.length>n?` ... +${x.length-n} more`:'')}
function overall():Status{return checks.some(c=>c.status==='FAIL')?'FAIL':checks.some(c=>c.status==='YELLOW')?'YELLOW':'PASS'}
function lits(block:string){return uniq([...block.matchAll(/["']([A-Za-z0-9_]+)["']/g)].map(m=>m[1]))}
function bFields(mapper:string){const out:string[]=[]; for(const m of mapper.matchAll(/const\s+B[A-Z0-9_]+\s*=\s*\[([\s\S]*?)\];/g)) out.push(...lits(m[1])); return uniq(out)}
function excluded(mapper:string){const m=mapper.match(/IDX_PLUS_EXCLUDED_FIELDS\s*=\s*new\s+Set\s*\(\s*\[([\s\S]*?)\]\s*\)/); return m?lits(m[1]):[]}
function renames(mapper:string){const m=mapper.match(/RESO_TO_RLS_RENAMES[^{]*\{([\s\S]*?)\};/); const r:Record<string,string>={}; if(!m)return r; for(const row of m[1].matchAll(/([A-Za-z0-9_]+)\s*:\s*["']([A-Za-z0-9_]+)["']/g)) r[row[1]]=row[2]; return r}
function metaFields(xml:string){if(!xml)return[]; const m=xml.match(/<EntityType\s+Name=["']Property["'][^>]*>([\s\S]*?)<\/EntityType>/); const scope=m?m[1]:xml; return uniq([...scope.matchAll(/<Property\s+Name=["']([^"']+)["']/g)].map(x=>x[1]))}
function csvFields(csv:string){const out:string[]=[]; for(const line of csv.split(/\r?\n/).slice(1)){ if(!line.trim())continue; const cells=line.split(',').map(c=>c.trim().replace(/^"|"$/g,'')); if(cells[1])out.push(cells[1]); if(cells[3])out.push(cells[3]); } return uniq(out)}
function iface(src:string,name:string){const s=src.indexOf(`export interface ${name}`); if(s<0)return''; const o=src.indexOf('{',s); let d=0; for(let i=o;i<src.length;i++){if(src[i]==='{')d++; if(src[i]==='}')d--; if(d===0)return src.slice(o+1,i)} return''}
async function token(){const id=process.env.IDX_CLIENT_ID||process.env.IDX_API_KEY; const sec=process.env.IDX_CLIENT_SECRET||process.env.IDX_API_SECRET; if(!id||!sec)return null; const base=process.env.TRESTLE_API_URL||process.env.IDX_ENDPOINT||'https://api.cotality.com/trestle'; const body=new URLSearchParams({grant_type:'client_credentials',client_id:id,client_secret:sec,scope:'api'}); const res=await fetch(`${base}/oidc/connect/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}); if(!res.ok)throw new Error(`token request failed ${res.status}`); const j=await res.json() as {access_token?:string}; return j.access_token||null}
async function liveMetadata(){const t=await token(); if(!t)return null; const base=process.env.TRESTLE_API_URL||process.env.IDX_ENDPOINT||'https://api.cotality.com/trestle'; const res=await fetch(`${base}/odata/$metadata`,{headers:{Authorization:`Bearer ${t}`}}); if(!res.ok)throw new Error(`metadata request failed ${res.status}`); return res.text()}
async function probe(base:string,part:string){const res=await fetch(`${base.replace(/\/$/,'')}${part}`,{redirect:'manual'}); return {status:res.status,body:await res.text().catch(()=>''),location:res.headers.get('location')||''}}
async function main(){
 const missingFiles=required.filter(f=>!exists(f)); add('G-000','Required Sentinel-G source files exist',missingFiles.length?'FAIL':'PASS',missingFiles.length?`Missing: ${missingFiles.join(', ')}`:`${required.length} required files found.`);
 const mapper=exists('lib/idx/trestle-mapper.ts')?read('lib/idx/trestle-mapper.ts'):''; const publicDto=exists('lib/idx/public-dto.ts')?read('lib/idx/public-dto.ts'):''; const dbDto=exists('lib/idx/db-to-public-dto.ts')?read('lib/idx/db-to-public-dto.ts'):''; const fetchTs=exists('lib/idx/fetch.ts')?read('lib/idx/fetch.ts'):''; const suggest=exists('app/api/listings/suggest/route.ts')?read('app/api/listings/suggest/route.ts'):''; const listingRoute=exists('app/api/listings/route.ts')?read('app/api/listings/route.ts'):''; const apiDetail=exists('app/api/listings/[id]/route.ts')?read('app/api/listings/[id]/route.ts'):''; const pageDetail=exists('app/listing/[id]/page.tsx')?read('app/listing/[id]/page.tsx'):''; const slug=exists('lib/listing-slug.ts')?read('lib/listing-slug.ts'):''; const idxCsv=exists('data/rebny-rls-property-fields.csv')?read('data/rebny-rls-property-fields.csv'):''; let metadata=exists('artifacts/metadata.xml')?read('artifacts/metadata.xml'):''; let mode:'static'|'static+live'='static';
 const all=bFields(mapper), exc=excluded(mapper), excSet=set(exc), selected=all.filter(f=>!excSet.has(f)), rn=renames(mapper), registry=csvFields(idxCsv), registrySet=set(registry);
 const m1=miss(mapper,['RESO_TO_RLS_RENAMES','IDX_PLUS_SELECT_FIELDS','computeGateColumns','InternetEntireListingDisplayYN','InternetAddressDisplayYN','Permission']); add('G-001','Mapper exposes required contract primitives',m1.length?'FAIL':'PASS',m1.length?`Missing anchors: ${m1.join(', ')}`:`Found ${all.length} B-category fields, ${exc.length} exclusions, ${selected.length} selected fields.`);
 const badExc=selected.filter(f=>excSet.has(f)); add('G-002','Excluded IDX Plus fields are not selected',badExc.length?'FAIL':'PASS',badExc.length?`Excluded fields still selected: ${sample(badExc)}`:`${exc.length} excluded fields absent from selected set.`);
 try{const live=await liveMetadata(); if(live){metadata=live; mode='static+live'; add('G-003','Live Cotality/Trestle metadata fetch','PASS','Fetched live /odata/$metadata with configured IDX credentials.')}else add('G-003','Live Cotality/Trestle metadata fetch','YELLOW','IDX credentials not configured; using artifacts/metadata.xml plus IDX Plus CSV registry.')}catch(e){add('G-003','Live Cotality/Trestle metadata fetch','FAIL',`Live metadata fetch failed: ${e instanceof Error?e.message:String(e)}`)}
 const meta=metaFields(metadata), metaSet=set(meta), hash=metadata?crypto.createHash('sha256').update(metadata).digest('hex'):null; add('G-004','Metadata and IDX Plus registry are readable',meta.length&&registry.length?'PASS':'FAIL',`${meta.length} Property metadata fields parsed. ${registry.length} IDX Plus registry fields parsed. sha256=${hash}`);
 const unresolved=selected.filter(f=>{const r=rn[f]; return !metaSet.has(f)&&!(r&&metaSet.has(r))&&!registrySet.has(f)&&!(r&&registrySet.has(r))}); add('G-005','Selected fields exist in metadata or IDX Plus registry after rename resolution',unresolved.length?'FAIL':'PASS',unresolved.length?`${unresolved.length} selected fields missing after metadata/registry/rename resolution: ${sample(unresolved)}`:`${selected.length} selected fields validated against Property metadata, IDX Plus CSV registry, or rename target.`);
 const badRn=Object.entries(rn).filter(([s,d])=>!s||!d||s===d); const rnMiss=Object.keys(rn).filter(s=>!all.includes(s)&&!metaSet.has(s)&&!registrySet.has(s)); add('G-006','RESO_TO_RLS_RENAMES has valid shape and source coverage',badRn.length?'FAIL':rnMiss.length?'YELLOW':'PASS',badRn.length?`Bad rename rows: ${sample(badRn.map(([s,d])=>`${s}->${d}`))}`:rnMiss.length?`Rename sources not in B arrays/metadata/registry, review as internal aliases: ${sample(rnMiss)}`:`${Object.keys(rn).length} rename rows covered.`);
 const idMissing=['ListingId','ListingKey','SourceSystemKey','OriginatingSystemKey','ListingKeyNumeric'].filter(f=>!all.includes(f)&&!metaSet.has(f)&&!registrySet.has(f)&&!(rn[f]&&(metaSet.has(rn[f])||registrySet.has(rn[f])))); const fetchMiss=miss(fetchTs,['ListingId eq','fetchSingleListing','ListingId != entity key']); add('G-007','Provider ID chain fields and fetch semantics are present',idMissing.length||fetchMiss.length?'FAIL':'PASS',idMissing.length||fetchMiss.length?`Missing ID fields/anchors: ${sample([...idMissing,...fetchMiss])}`:'Provider ID chain and ListingId fetch semantics found.');
 const dto=iface(publicDto,'PublicListingDTO'); const dtoLeaks=forbidden.filter(k=>new RegExp(`\\b${k}\\b`).test(dto)); const dtoMiss=miss(publicDto,['_displayCompliance','requiresAttribution','attributionText','disclaimerRequired','isAddressDisplayable','generateListingSlug']); add('G-008','Public DTO has attribution/canonical fields and no internal fields in DTO shape',dtoLeaks.length||dtoMiss.length?'FAIL':'PASS',dtoLeaks.length||dtoMiss.length?`DTO leaks=${dtoLeaks.join(', ')||'none'} missing=${dtoMiss.join(', ')||'none'}`:'Public DTO shape is clean.');
 const dbMiss=miss(dbDto,['classifyDbListing','mallan-exclusive','third-party-idx','website-only','filterDisplayableDbListings','owner_client_id','agent_id','rls_eligible']); add('G-009','DB DTO classifies Mallan exclusive vs third-party IDX vs website-only',dbMiss.length?'FAIL':'PASS',dbMiss.length?`Missing DB classification anchors: ${dbMiss.join(', ')}`:'DB provenance classifier anchors found.');
 const gateMiss=miss(mapper+dbDto+suggest+listingRoute,['computeGateColumns','filterDisplayableDbListings','checkDistributionGates','InternetEntireListingDisplayYN','InternetAddressDisplayYN','owner_opt_out','participant_only']); add('G-010','Display gates are represented across mapper, DB DTO, suggest, and listing route',gateMiss.length?'FAIL':'PASS',gateMiss.length?`Missing gate anchors: ${gateMiss.join(', ')}`:'Display gate anchors found across layers.');
 const sugMiss=miss(suggest,['SUGGEST_SELECT_FIELDS','ListingId','ListingKey','checkDistributionGates','isAddressDisplayablePerSuggest','InternetAddressDisplayYN','InternetEntireListingDisplayYN']); const sugLeaks=forbidden.filter(k=>new RegExp(`\\b${k}\\b`).test(suggest)); add('G-011','Public suggest route uses identity/gate anchors and avoids private fields',sugMiss.length||sugLeaks.length?'FAIL':'PASS',sugMiss.length||sugLeaks.length?`suggest missing=${sugMiss.join(', ')||'none'} private-key-presence=${sugLeaks.join(', ')||'none'}`:'Suggest route identity/gate anchors clean.');
 const slugMiss=miss(slug,['generateListingSlug','extractListingIdFromSlug','extractMlsIdFromSlug','isMlsIdSlug','internetAddressDisplayYN','listing-']); const pageMiss=miss(pageDetail,['extractListingIdFromSlug','extractMlsIdFromSlug','parseAddressSlug','generateListingSlug']); add('G-012','Public detail page supports canonical address slug plus fallback ID resolution',slugMiss.length||pageMiss.length?'FAIL':'PASS',slugMiss.length||pageMiss.length?`slug missing=${slugMiss.join(', ')||'none'} page missing=${pageMiss.join(', ')||'none'}`:'Slug helper and public detail page anchors found.');
 const routeMiss=miss(listingRoute,['filterDisplayableDbListings','annotateCoListedSiblings']); add('G-013','Public listing route applies display filtering and sibling annotation',routeMiss.length?'FAIL':'PASS',routeMiss.length?`Missing listing route anchors: ${routeMiss.join(', ')}`:'Public listing route anchors found.');
 const apiMiss=miss(apiDetail,['fetchSingleListing','checkDistributionGates','toPublicDTO']); add('G-014','Public API detail route remains ID-oriented while page route handles slugs',apiMiss.length?'FAIL':'PASS',apiMiss.length?`Missing API detail route anchors: ${apiMiss.join(', ')}`:'API route validated separately from page slug route.');
 const base=process.env.SENTINEL_G_BASE_URL||process.env.NEXT_PUBLIC_SITE_URL||''; if(base){for(const q of ['/api/listings/suggest?q=SL-0004','/api/listings/suggest?q=333%20E%2046','/api/listings?address=333%20E%2046','/listing/sl-0004']){try{const r=await probe(base,q); const leaks=forbidden.filter(k=>r.body.includes(k)); const fallbackShown=q!=='/listing/sl-0004'&&r.body.includes('/listing/sl-0004'); const ok=q==='/listing/sl-0004'?[200,301,302,307,308,404].includes(r.status):r.status<500; add('G-015',`Public endpoint probe ${q}`,leaks.length||fallbackShown||!ok?'FAIL':'PASS',`status=${r.status}${r.location?` location=${r.location}`:''}${leaks.length?` leaks=${leaks.join(',')}`:''}${fallbackShown?' fallback-url-displayed=true':''}`)}catch(e){add('G-015',`Public endpoint probe ${q}`,'FAIL',e instanceof Error?e.message:String(e))}}} else add('G-015','Public endpoint probes','YELLOW','SENTINEL_G_BASE_URL or NEXT_PUBLIC_SITE_URL not set; endpoint probes skipped, not passed.');
 const report={tool:'Sentinel-G' as const,status:overall(),generatedAt:new Date().toISOString(),mode,metadataHash:hash,selectedFieldCount:selected.length,metadataPropertyFieldCount:meta.length,idxRegistryFieldCount:registry.length,checks}; fs.mkdirSync(outDir,{recursive:true}); const jp=path.join(outDir,`${stamp}-report.json`), mp=path.join(outDir,`${stamp}-report.md`); fs.writeFileSync(jp,JSON.stringify(report,null,2)); fs.writeFileSync(mp,`# Sentinel-G Report\n\nStatus: **${report.status}**\n\nGenerated: ${report.generatedAt}\n\nMode: ${report.mode}\n\nSelected fields: ${report.selectedFieldCount}\n\nMetadata Property fields: ${report.metadataPropertyFieldCount}\n\nIDX Plus registry fields: ${report.idxRegistryFieldCount}\n\n| Code | Status | Check | Details |\n|---|---|---|---|\n${checks.map(c=>`| ${c.code} | ${c.status} | ${c.name} | ${c.details.replace(/\|/g,'\\|')} |`).join('\n')}\n`); console.log(`Sentinel-G status: ${report.status}`); console.log(`Mode: ${report.mode}`); console.log(`JSON report: ${path.relative(root,jp)}`); console.log(`Markdown report: ${path.relative(root,mp)}`); for(const c of checks) console.log(`${c.status.padEnd(6)} ${c.code} ${c.name}`); if(report.status==='FAIL')process.exit(1);
}
main().catch(e=>{add('G-999','Sentinel-G runner crashed','FAIL',e instanceof Error?(e.stack||e.message):String(e)); const report={tool:'Sentinel-G',status:'FAIL',generatedAt:new Date().toISOString(),mode:'static',metadataHash:null,selectedFieldCount:0,metadataPropertyFieldCount:0,idxRegistryFieldCount:0,checks}; fs.mkdirSync(outDir,{recursive:true}); fs.writeFileSync(path.join(outDir,`${stamp}-report.json`),JSON.stringify(report,null,2)); console.error(e); process.exit(1)});
