name: PR checks

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dev_user
          POSTGRES_PASSWORD: dev_password
          POSTGRES_DB: mallan
        ports:
          - 5432:5432
       